{
  "hash": "f361d2ef3fff1720bfaa454caca5f039",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"rpact\"\nsearch: true\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(\n  dev = \"png\",          \n  dpi = 300,\n  fig.width = 7,\n  fig.height = 5\n)\n\nlibrary(tidyverse)\nlibrary(rpact)\nlibrary(PWEXP)\n```\n:::\n\n\n\n\n## Links {-}\n\n+ [rpact website](https://www.rpact.org/#r-generics)\n+ [rpact start guide](https://manual.rpact.org/pdf/rpact_v4_2.1_quick_start_guide.pdf)\n+ [Step-by-step rpact tutorial](https://www.rpact.org/vignettes/getting-started/rpact_step-by-step_tutorial/)\n\n## Start {-}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create an inverse normal design with default parameters\ndesign <- getDesignInverseNormal()\n\ndesign %>% summary()\n```\n\n::: {.cell-output-display}\n*Sequential analysis with a maximum of 3 looks \n(inverse normal combination test design)*\n\nO'Brien & Fleming design, one-sided overall significance level 2.5%, power 80%, \nundefined endpoint, inflation factor 1.0174, ASN H1 0.8562, ASN H01 0.9831, \nASN H0 1.0149.\n\n| Stage                             |      1 |      2 |      3 |\n| ----- | ----- | ----- | ----- |\n| Fixed weight                      |  0.577 |  0.577 |  0.577 |\n| Cumulative alpha spent            | 0.0003 | 0.0072 | 0.0250 |\n| Stage levels (one-sided)          | 0.0003 | 0.0071 | 0.0225 |\n| Efficacy boundary (z-value scale) |  3.471 |  2.454 |  2.004 |\n| Cumulative power                  | 0.0329 | 0.4424 | 0.8000 |\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# display the design characteristics\ndesign %>% getDesignCharacteristics()\n```\n\n::: {.cell-output-display}\n*Inverse normal combination test design characteristics*\n\n* *Number of subjects fixed*: 7.8489 \n* *Shift*: 7.9855 \n* *Inflation factor*: 1.0174 \n* *Informations*: 2.662, 5.324, 7.985 \n* *Power*: 0.03292, 0.44240, 0.80000 \n* *Rejection probabilities under H1*: 0.03292, 0.40948, 0.35760 \n* *Futility probabilities under H1*: 0, 0 \n* *Ratio expected vs fixed sample size under H1*: 0.8562 \n* *Ratio expected vs fixed sample size under a value between H0 and H1*: 0.9831 \n* *Ratio expected vs fixed sample size under H0*: 1.0149 \n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot the design with default type 1 (Boundary Plot)\ndesign %>% plot()\n```\n\n::: {.cell-output-display}\n![](rpact_files/figure-html/unnamed-chunk-4-1.png){width=2100}\n:::\n:::\n\n\n\n## Example: PFS simulation using protocol assumptions {-}\n\nThis is an example for simulating the PFS events to get the predicted projection time and confidence internval based on the protocol assumption, considering actual enrollment and drop out rate per month. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nii <- 1:100\n\nmon.enr.6 <- rep(40, 20)\nstart_date <- as.Date(\"2022-08-01\")\n\nget.followup.sap <- function(ii){\n    set.seed(92480+ii)\n    dat.sap.sim <- \n      simdata(group=c('trt','ctrl'), \n              allocation = c(1, 1), \n              n_rand = mon.enr.6, ## real enrollment\n              event_lambda = c(log(2)/20*0.75,\n                               log(2)/20),\n              drop_rate = 0.008,  ## monthly rate\n              total_sample = 800,\n              add_column = c('followT','event', 'followT_abs','censor'))\n    enr2 <- dat.sap.sim %>% \n      filter(event == 1) %>% \n      arrange(followT_abs) \n    return(enr2 %>% select(followT_abs) %>% \n             slice(c(344, 458)))\n}\n \nsuppressMessages(\n  sim.res.sap <- map_dfc(.x = ii, .f = get.followup.sap)\n)\n\nsim.res.sap.df <- as.data.frame(sim.res.sap)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# interim analysis \nx344 <- quantile((as.numeric(sim.res.sap.df[1, ])), \n                 probs = c(0.025, 0.5, 0.975))\nx344\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%      50%    97.5% \n28.94270 31.43274 33.65996 \n```\n\n\n:::\n\n```{.r .cell-code}\nstart_date + x344*30.4375\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        2.5%          50%        97.5% \n\"2024-12-28\" \"2025-03-14\" \"2025-05-21\" \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# final analysis \nx458 <- quantile((as.numeric(sim.res.sap.df[2, ])), \n                 probs = c(0.025, 0.5, 0.975))\nx458\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%      50%    97.5% \n39.86313 44.67826 49.11732 \n```\n\n\n:::\n\n```{.r .cell-code}\nstart_date+ x458*30.4375\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        2.5%          50%        97.5% \n\"2025-11-26\" \"2026-04-21\" \"2026-09-04\" \n```\n\n\n:::\n:::\n\n\n\n\n## Example: event prediction based on the actual data {-}\n\n#### Simulate PFS data {-}\n\nSuppuse the actual follow up time is 36 months. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12345)\n\nmon.enr.6 <- rep(40, 20)\n\ndata <- dat.sap.sim <- \n      simdata(group=c('trt','ctrl'), \n              allocation = c(1, 1), \n              n_rand = mon.enr.6, ## real enrollment\n              event_lambda = c(log(2)/25*0.5,\n                               log(2)/25),\n              drop_rate = 0.0065,  ## monthly rate\n              total_sample = 800,\n              add_column = c('followT','event', 'followT_abs','censor')) %>% \n  mutate(drop = as.numeric((followT_abs <= 36) & (censor == 1))) %>% \n  mutate(censor = as.numeric(drop == 1 | followT_abs > 36)) %>% \n  mutate(followT_abs = pmin(36, followT_abs), \n         followT = pmin(followT, 36 - randT)) %>% \n  mutate(event = 1 - censor)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ID group     randT     eventT      dropT   followT event followT_abs censor\n1  1   trt 18.030343 135.339681  72.068327 17.969657     0    36.00000      1\n2  2   trt 11.598061  27.124264   3.811665  3.811665     0    15.40973      1\n3  3   trt  5.295963  68.441549  34.330874 30.704037     0    36.00000      1\n4  4   trt 12.396894 130.057004 335.566711 23.603106     0    36.00000      1\n5  5   trt  9.678056  27.298814 117.665749 26.321944     0    36.00000      1\n6  6   trt 12.774233   9.732452 127.038945  9.732452     1    22.50669      0\n  drop\n1    0\n2    1\n3    0\n4    0\n5    0\n6    0\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(data$event)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  0   1 \n492 308 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(data$drop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  0   1 \n707  93 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_b1 <- pwexp.fit(data$followT, data$event, nbreak = 1)  \nfit_b1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        brk1       lam1       lam2 likelihood      AIC      BIC\n108 4.358788 0.02780412 0.01929306  -1491.098 2988.195 3002.249\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_survival(data$followT, data$drop,  \n              ylab='Survival function of drop-out', \n              main='Fitted Model with 95% CI')\n```\n\n::: {.cell-output-display}\n![](rpact_files/figure-html/unnamed-chunk-12-1.png){width=2100}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ninvisible(capture.output(\n  fit_b1_boot <- boot.pwexp.fit(fit_b1, nsim = 100, seed = 0102)\n))\n\ninvisible(capture.output(\n  fit_censor_boot1 <- boot.pwexp.fit(data$followT, \n                                   data$drop, nbreak = 1, \n                                   nsim = 100, seed=0102)\n))\n\ncut_indicator = 1- data$event\ncut_indicator[data$drop==1]=0;\n\nanat=(as.Date(\"2025-08-01\") -\n        as.Date(\"2022-08-01\"))/30.4375\n\npredicted_boot11 <- predict(fit_b1_boot, \n                            cut_indicator=cut_indicator,\n                            analysis_time=anat,\n                            censor_model_boot=fit_censor_boot1,\n                            future_rand=NULL,seed=0102,\n                            output = \"summary\" )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.new()\npred_time11 <- plot_event(predicted_boot11, xyswitch=T, \n                          eval_at = c(344,458), alpha = 0.05)\n```\n\n::: {.cell-output-display}\n![](rpact_files/figure-html/unnamed-chunk-14-1.png){width=2100}\n:::\n\n```{.r .cell-code}\npred_time11\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     n_event     time 2.5% time 97.5% time\n[1,]     344 40.64383  38.42825   42.24332\n[2,]     458 61.96626  46.44132   71.34709\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsumDt11 =as.data.frame(pred_time11); \nsumDt11$time =start_date + as.data.frame(pred_time11)$time*30.4375\nsumDt11$`2.5% time` = start_date + as.data.frame(pred_time11)$`2.5% time`*30.4375; \nsumDt11$`97.5% time` = start_date + as.data.frame(pred_time11)$`97.5% time`*30.4375;\n\nsumDt11\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  n_event       time  2.5% time 97.5% time\n1     344 2025-12-20 2025-10-13 2026-02-06\n2     458 2027-09-30 2026-06-14 2028-07-11\n```\n\n\n:::\n:::\n\n\n\n\n#### Event curve plot {-}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccrualTime <- \n  getAccrualTime(accrualTime = 0:(20-1), \n                 accrualIntensity = rep(40, 20), \n                 maxNumberOfSubjects = 800)\n\ny <- getEventProbabilities(time = 1:80, \n                           lambda2 = log(2)/20, \n                           accrualTime = accrualTime,\n                           hazardRatio = 0.5, \n                           allocationRatioPlanned = 1)\nplot_obj <- rpact:::plot.EventProbabilities(y, plot = FALSE)\n```\n\n::: {.cell-output-display}\n![](rpact_files/figure-html/unnamed-chunk-16-1.png){width=2100}\n:::\n\n```{.r .cell-code}\nyValues <- plot_obj$data$yValues\n\nplot_event(data$followT_abs, data$event, ylim = c(0, 500), \n           xlim = c(0, 80), col = \"blue\", main = \"Event Curve\", cex.axis = 0.65)\nplot_event(predicted_boot11)\n\nlines(x = 1:80, y = yValues[1:80], col = \"grey30\", lwd = 2)\n\nlegend(\"topleft\", c(\"Actual\", \"CI\", \"Planned\"), col = c(\"blue\", \"red\", \"grey30\"),\n       lwd = 2, cex = 0.65)\n```\n\n::: {.cell-output-display}\n![](rpact_files/figure-html/unnamed-chunk-16-2.png){width=2100}\n:::\n:::\n",
    "supporting": [
      "rpact_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}