<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Multiple Myeloma – Hao Sun</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../docs/pharmaceutical/disease/Melanoma.html" rel="next">
<link href="../../../docs/pharmaceutical/disease/MDS.html" rel="prev">
<link href="../../../favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-40bff128ebd1d07c10ce41ee10634112.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
<meta property="og:title" content="Multiple Myeloma – Hao Sun">
<meta property="og:description" content="">
<meta property="og:image" content="BMS.png">
<meta property="og:site_name" content="Hao Sun">
<meta name="twitter:title" content="Multiple Myeloma – Hao Sun">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="BMS.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../BMS.png" alt="BMS logo." class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/statistics/index.html"> 
<span class="menu-text">Statistics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/programming/index.html"> 
<span class="menu-text">Programming</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/visualization/index.html"> 
<span class="menu-text">Visualization</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/pharmaceutical/index.html"> 
<span class="menu-text">Pharmaceutical</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://twitter.com/eugenesun14" title="Quarto Twitter" class="quarto-navigation-tool px-1" aria-label="Quarto Twitter"><i class="bi bi-twitter"></i></a>
    <a href="https://github.com/EugeneHao" title="Quarto GitHub" class="quarto-navigation-tool px-1" aria-label="Quarto GitHub"><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/in/hao-sun-13207/" title="Quarto Linkedin" class="quarto-navigation-tool px-1" aria-label="Quarto Linkedin"><i class="bi bi-linkedin"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../docs/pharmaceutical/listing-company.html">Pharmaceutical Content</a></li><li class="breadcrumb-item"><a href="../../../docs/pharmaceutical/listing-disease.html">Disease</a></li><li class="breadcrumb-item"><a href="../../../docs/pharmaceutical/disease/Leukemia.html">Bone Marrow</a></li><li class="breadcrumb-item"><a href="../../../docs/pharmaceutical/disease/multiple_myeloma.html">Multiple Myeloma (MM)</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/listing-company.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pharmaceutical Content</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/listing-company.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Company</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/company/BMS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">BMS</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Eliquis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eliquis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Opdivo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Opdivo</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Reblozyl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reblozyl</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Revlimid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Revlimid</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Yervoy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Yervoy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Onureg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Onureg</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Inrebic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inrebic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Iberdomide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Iberdomide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Mezigdomide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mezigdomide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Alnuctamab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Alnuctamab</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Abecma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abecma</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Breyanzi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Breyanzi</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Krazati.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Krazati</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/KarXT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">KarXT (COBENFY)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Pumitamig.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pumitamig</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Izalontamab_Brengitecan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Izalontamab Brengitecan</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/company/Akeso.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Akeso</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Ivonescimab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ivonescimab</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Cadonilimab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cadonilimab</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/company/Summit_Therapeutics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summit Therapeutics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Ivonescimab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ivonescimab</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/company/Merck.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Merck</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Keytruda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Keytruda</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Januvia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Januvia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Gardasil.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gardasil</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Lynparza.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lynparza</span></a>
  </div>
</li>
          <li class="sidebar-item">
 <span class="menu-text">Pneumovax</span>
  </li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/company/AstraZeneca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AstraZeneca</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Imfinzi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Imfinzi</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Lynparza.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lynparza</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/company/J &amp; J.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">J &amp; J</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Carvykti.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Carvykti</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Tecvayli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tecvayli</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Darzalex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Darzalex</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Remicade.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Remicade</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Stelara.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stelara</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Xarelto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Xarelto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Bortezomib.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bortezomib</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/company/Pfizer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pfizer</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Mylotarg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mylotarg</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Comirnaty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Comirnaty</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Prevnar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prevnar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Ibrance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ibrance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Xeljanz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Xeljanz</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Xalkori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Xalkori</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Sirolimus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sirolimus</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/company/Roche.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Roche</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Tecentriq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tecentriq</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Rituxan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rituxan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Herceptin.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Herceptin</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Avastin.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Avastin</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Zelboraf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Zelboraf</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Cotellic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cotellic</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/company/Abbvie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abbvie</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Humira.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Humira</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/company/GSK.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GSK</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Tafinlar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tafinlar</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/company/Novartis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Novartis</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Mekinist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mekinist</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/company/Sanofi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sanofi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Docetaxel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Taxotere</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">Incyte</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Jakafi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Jakafi</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">Vertex</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Kalydeco.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kalydeco</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/company/Regeneron.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regeneron</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/company/Gilead.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gilead</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false">
 <span class="menu-text">Amgen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Carfilzomib.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Carfilzomib</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Regulatory</span></span>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/listing-compound.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Compound</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/compound/Venclexta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Venclexta</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/listing-disease.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Disease</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="true">
 <span class="menu-text">Bone Marrow</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth3 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/disease/Leukemia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Leukemia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/disease/Lymphoma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lymphoma</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/disease/MDS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Myelodysplastic Syndromes (MDS)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/disease/multiple_myeloma.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Multiple Myeloma (MM)</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/disease/Melanoma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Melanoma</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/disease/Breast_Cancer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Breast Cancer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/disease/Lung_Cancer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lung Cancer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/disease/NSCLC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Non-Small Cell Lung Cancer (NSCLC)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/disease/SCLC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Small Cell Lung Cancer (SCLC)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/disease/T2DM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Type 2 Diabete Mellitus (T2DM)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/disease/Thrombosis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thrombosis</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/listing-target.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Target</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-22" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-22" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/target/PD-L1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PD-L1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/target/VEGF.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">VEGF</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/target/HER.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HER Family</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/target/TROP2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TROP2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/target/KRAS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">KRAS</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/listing-SDTM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SDTM</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../docs/pharmaceutical/listing-other.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Other</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-23" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-23" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-24" role="navigation" aria-expanded="false">
 <span class="menu-text">Wiki</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-24" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-24" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-25" role="navigation" aria-expanded="false">
 <span class="menu-text">Biotechnology</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-25" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-25" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/other/Drug.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General Drug Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/other/ADC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Antibody-Drug Conjugates (ADC)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/other/CAR-T.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">CAR-T</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/other/Immune_Checkpoint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Immune Checkpoint</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/other/Immunotherapy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Immunotherapy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/other/MAT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Monoclonal Antibody Therapy (MAT)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/other/TME.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tumor Microenvironment (TME)</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-26" role="navigation" aria-expanded="false">
 <span class="menu-text">Clinical Trial</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-26" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-26" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/AE/AE_SOC_PT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Adverse Event by SOC and PT</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/other/Biomarker.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Biomarker</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/other/Intercurrent_Events.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Intercurrent Events</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/other/TNM_Staging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TNM Staging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/other/ECOG_Performance_Status.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ECOG Performance Status</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/other/RECIST_1_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RECIST 1.1</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Endpoint</span></span>
  </li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/wiki/pharma_note.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pharma Note</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/pharmaceutical/wiki/Naming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Drug Naming Rules</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#背景" id="toc-背景" class="nav-link active" data-scroll-target="#背景">背景</a>
  <ul class="collapse">
  <li><a href="#骨骼的主要功能key-functions-of-bones" id="toc-骨骼的主要功能key-functions-of-bones" class="nav-link" data-scroll-target="#骨骼的主要功能key-functions-of-bones">骨骼的主要功能（Key functions of bones）</a></li>
  <li><a href="#骨代谢bone-metabolism-和-骨重塑bone-remodeling" id="toc-骨代谢bone-metabolism-和-骨重塑bone-remodeling" class="nav-link" data-scroll-target="#骨代谢bone-metabolism-和-骨重塑bone-remodeling">骨代谢（Bone metabolism） 和 骨重塑（Bone remodeling）</a></li>
  <li><a href="#骨组织-bone-tissue-与骨髓结构-bone-marrow" id="toc-骨组织-bone-tissue-与骨髓结构-bone-marrow" class="nav-link" data-scroll-target="#骨组织-bone-tissue-与骨髓结构-bone-marrow">骨组织 (Bone Tissue) 与骨髓结构 (Bone Marrow)</a></li>
  <li><a href="#造血-hematopoiesis" id="toc-造血-hematopoiesis" class="nav-link" data-scroll-target="#造血-hematopoiesis">造血 (Hematopoiesis)</a></li>
  <li><a href="#浆细胞与抗体功能plasma-cells-and-antibodies" id="toc-浆细胞与抗体功能plasma-cells-and-antibodies" class="nav-link" data-scroll-target="#浆细胞与抗体功能plasma-cells-and-antibodies">浆细胞与抗体功能（Plasma Cells and Antibodies）</a></li>
  <li><a href="#浆细胞肿瘤plasma-cell-neoplasms" id="toc-浆细胞肿瘤plasma-cell-neoplasms" class="nav-link" data-scroll-target="#浆细胞肿瘤plasma-cell-neoplasms">浆细胞肿瘤（Plasma Cell Neoplasms）</a></li>
  </ul></li>
  <li><a href="#发病机制pathogenesis" id="toc-发病机制pathogenesis" class="nav-link" data-scroll-target="#发病机制pathogenesis">发病机制（Pathogenesis）</a></li>
  <li><a href="#遗传学机制genetics" id="toc-遗传学机制genetics" class="nav-link" data-scroll-target="#遗传学机制genetics">遗传学机制（Genetics）</a></li>
  <li><a href="#流行病学与趋势prevalence-and-trends" id="toc-流行病学与趋势prevalence-and-trends" class="nav-link" data-scroll-target="#流行病学与趋势prevalence-and-trends">流行病学与趋势（Prevalence and Trends）</a></li>
  <li><a href="#临床表现与症状signs-and-symptoms" id="toc-临床表现与症状signs-and-symptoms" class="nav-link" data-scroll-target="#临床表现与症状signs-and-symptoms">临床表现与症状（Signs and Symptoms）</a></li>
  <li><a href="#diagnosis" id="toc-diagnosis" class="nav-link" data-scroll-target="#diagnosis">Diagnosis</a>
  <ul class="collapse">
  <li><a href="#检测与诊断multiple-myeloma-testing" id="toc-检测与诊断multiple-myeloma-testing" class="nav-link" data-scroll-target="#检测与诊断multiple-myeloma-testing">检测与诊断（Multiple Myeloma Testing）</a></li>
  <li><a href="#crab-criteria-for-diagnosis" id="toc-crab-criteria-for-diagnosis" class="nav-link" data-scroll-target="#crab-criteria-for-diagnosis">CRAB Criteria for Diagnosis</a></li>
  <li><a href="#laboratory-tests" id="toc-laboratory-tests" class="nav-link" data-scroll-target="#laboratory-tests">Laboratory Tests</a></li>
  <li><a href="#活检biopsies" id="toc-活检biopsies" class="nav-link" data-scroll-target="#活检biopsies">活检（Biopsies）</a></li>
  <li><a href="#imaging-tests" id="toc-imaging-tests" class="nav-link" data-scroll-target="#imaging-tests">Imaging Tests</a></li>
  <li><a href="#诊断标准establishing-the-diagnosis" id="toc-诊断标准establishing-the-diagnosis" class="nav-link" data-scroll-target="#诊断标准establishing-the-diagnosis">诊断标准（Establishing the Diagnosis）</a></li>
  </ul></li>
  <li><a href="#other-disease-information" id="toc-other-disease-information" class="nav-link" data-scroll-target="#other-disease-information">Other Disease Information</a>
  <ul class="collapse">
  <li><a href="#imwg-frailty-score" id="toc-imwg-frailty-score" class="nav-link" data-scroll-target="#imwg-frailty-score">IMWG Frailty Score</a></li>
  <li><a href="#common-baseline-requirement" id="toc-common-baseline-requirement" class="nav-link" data-scroll-target="#common-baseline-requirement">Common Baseline Requirement</a></li>
  <li><a href="#issinternational-staging-system-国际分期系统2005-年提出" id="toc-issinternational-staging-system-国际分期系统2005-年提出" class="nav-link" data-scroll-target="#issinternational-staging-system-国际分期系统2005-年提出">ISS（International Staging System, 国际分期系统，2005 年提出）</a></li>
  <li><a href="#r-issrevised-iss修订版国际分期系统2015-年提出" id="toc-r-issrevised-iss修订版国际分期系统2015-年提出" class="nav-link" data-scroll-target="#r-issrevised-iss修订版国际分期系统2015-年提出">R-ISS（Revised ISS，修订版国际分期系统，2015 年提出）</a></li>
  <li><a href="#type-of-heavy-chain-and-light-chain" id="toc-type-of-heavy-chain-and-light-chain" class="nav-link" data-scroll-target="#type-of-heavy-chain-and-light-chain">Type of Heavy Chain and Light Chain</a></li>
  <li><a href="#extramedullary-plasmacytomas-emps骨髓外浆细胞瘤" id="toc-extramedullary-plasmacytomas-emps骨髓外浆细胞瘤" class="nav-link" data-scroll-target="#extramedullary-plasmacytomas-emps骨髓外浆细胞瘤">Extramedullary Plasmacytomas (EMPs，骨髓外浆细胞瘤)</a></li>
  </ul></li>
  <li><a href="#治疗" id="toc-治疗" class="nav-link" data-scroll-target="#治疗">治疗</a>
  <ul class="collapse">
  <li><a href="#一线治疗frontline-newly-diagnosed" id="toc-一线治疗frontline-newly-diagnosed" class="nav-link" data-scroll-target="#一线治疗frontline-newly-diagnosed">一线治疗（Frontline / Newly Diagnosed）</a></li>
  <li><a href="#二线治疗relapsed-refractory-mm-second-line" id="toc-二线治疗relapsed-refractory-mm-second-line" class="nav-link" data-scroll-target="#二线治疗relapsed-refractory-mm-second-line">二线治疗（Relapsed / Refractory MM, Second Line）</a></li>
  <li><a href="#三线治疗third-line" id="toc-三线治疗third-line" class="nav-link" data-scroll-target="#三线治疗third-line">三线治疗（Third Line）</a></li>
  <li><a href="#四线及之后治疗fourth-line-and-beyond" id="toc-四线及之后治疗fourth-line-and-beyond" class="nav-link" data-scroll-target="#四线及之后治疗fourth-line-and-beyond">四线及之后治疗（Fourth Line and Beyond）</a></li>
  <li><a href="#therapy-for-previously-treated-multiple-myeloma" id="toc-therapy-for-previously-treated-multiple-myeloma" class="nav-link" data-scroll-target="#therapy-for-previously-treated-multiple-myeloma">Therapy for Previously Treated Multiple Myeloma</a></li>
  <li><a href="#维持治疗-maintenance-therapy" id="toc-维持治疗-maintenance-therapy" class="nav-link" data-scroll-target="#维持治疗-maintenance-therapy">维持治疗 (Maintenance Therapy)</a></li>
  </ul></li>
  <li><a href="#药物" id="toc-药物" class="nav-link" data-scroll-target="#药物">药物</a>
  <ul class="collapse">
  <li><a href="#蛋白酶体抑制剂proteasome-inhibitors" id="toc-蛋白酶体抑制剂proteasome-inhibitors" class="nav-link" data-scroll-target="#蛋白酶体抑制剂proteasome-inhibitors">蛋白酶体抑制剂（Proteasome Inhibitors）</a></li>
  <li><a href="#免疫调节剂immunomodulatory-drugs-imids" id="toc-免疫调节剂immunomodulatory-drugs-imids" class="nav-link" data-scroll-target="#免疫调节剂immunomodulatory-drugs-imids">免疫调节剂（Immunomodulatory Drugs, IMiDs）</a></li>
  <li><a href="#corticosteroids糖皮质激素" id="toc-corticosteroids糖皮质激素" class="nav-link" data-scroll-target="#corticosteroids糖皮质激素">Corticosteroids（糖皮质激素）</a></li>
  <li><a href="#chemotherapeutics化疗药物" id="toc-chemotherapeutics化疗药物" class="nav-link" data-scroll-target="#chemotherapeutics化疗药物">Chemotherapeutics（化疗药物）</a></li>
  <li><a href="#stem-cell-transplantation干细胞移植" id="toc-stem-cell-transplantation干细胞移植" class="nav-link" data-scroll-target="#stem-cell-transplantation干细胞移植">Stem Cell Transplantation（干细胞移植）</a></li>
  <li><a href="#monoclonal-antibodies单克隆抗体" id="toc-monoclonal-antibodies单克隆抗体" class="nav-link" data-scroll-target="#monoclonal-antibodies单克隆抗体">Monoclonal Antibodies（单克隆抗体）</a></li>
  <li><a href="#car-t-cell-therapycar-t-细胞疗法" id="toc-car-t-cell-therapycar-t-细胞疗法" class="nav-link" data-scroll-target="#car-t-cell-therapycar-t-细胞疗法">CAR T-Cell Therapy（CAR-T 细胞疗法）</a></li>
  <li><a href="#other-recently-approved-therapies近期获批疗法" id="toc-other-recently-approved-therapies近期获批疗法" class="nav-link" data-scroll-target="#other-recently-approved-therapies近期获批疗法">Other Recently Approved Therapies（近期获批疗法）</a></li>
  <li><a href="#支持治疗supportive-care" id="toc-支持治疗supportive-care" class="nav-link" data-scroll-target="#支持治疗supportive-care">支持治疗（Supportive care）</a></li>
  </ul></li>
  <li><a href="#responses-疗效反应标准" id="toc-responses-疗效反应标准" class="nav-link" data-scroll-target="#responses-疗效反应标准">Responses 疗效反应标准</a></li>
  <li><a href="#disease-progression" id="toc-disease-progression" class="nav-link" data-scroll-target="#disease-progression">Disease Progression</a></li>
  <li><a href="#treatment-strategy-for-different-patients" id="toc-treatment-strategy-for-different-patients" class="nav-link" data-scroll-target="#treatment-strategy-for-different-patients">Treatment Strategy for different patients</a>
  <ul class="collapse">
  <li><a href="#solitary-plasmacytoma-孤立性浆细胞瘤" id="toc-solitary-plasmacytoma-孤立性浆细胞瘤" class="nav-link" data-scroll-target="#solitary-plasmacytoma-孤立性浆细胞瘤">Solitary Plasmacytoma (孤立性浆细胞瘤)</a></li>
  <li><a href="#asymptomatic-myeloma" id="toc-asymptomatic-myeloma" class="nav-link" data-scroll-target="#asymptomatic-myeloma">Asymptomatic Myeloma</a></li>
  <li><a href="#active-myelomaprimary-therapy" id="toc-active-myelomaprimary-therapy" class="nav-link" data-scroll-target="#active-myelomaprimary-therapy">Active Myeloma（Primary Therapy）</a></li>
  <li><a href="#active-myelomapreferred-agents" id="toc-active-myelomapreferred-agents" class="nav-link" data-scroll-target="#active-myelomapreferred-agents">Active Myeloma（Preferred Agents）</a></li>
  <li><a href="#active-myelomasct" id="toc-active-myelomasct" class="nav-link" data-scroll-target="#active-myelomasct">Active Myeloma（SCT）</a></li>
  </ul></li>
  <li><a href="#与myeloma的关系" id="toc-与myeloma的关系" class="nav-link" data-scroll-target="#与myeloma的关系">与Myeloma的关系</a></li>
  <li><a href="#与aml的区别" id="toc-与aml的区别" class="nav-link" data-scroll-target="#与aml的区别">与AML的区别</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../docs/pharmaceutical/listing-company.html">Pharmaceutical Content</a></li><li class="breadcrumb-item"><a href="../../../docs/pharmaceutical/listing-disease.html">Disease</a></li><li class="breadcrumb-item"><a href="../../../docs/pharmaceutical/disease/Leukemia.html">Bone Marrow</a></li><li class="breadcrumb-item"><a href="../../../docs/pharmaceutical/disease/multiple_myeloma.html">Multiple Myeloma (MM)</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Multiple Myeloma</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>多发性骨髓瘤（Multiple Myeloma，MM）是一种发生在血液中的癌症，特别影响称为浆细胞（plasma cells）的白细胞（white blood cells）。浆细胞在健康人体中帮助抵抗感染（fight infections），但在多发性骨髓瘤中，这些恶性浆细胞（malignant plasma cells, 恶性浆细胞）异常增生（abnormal proliferation）并积聚在骨髓（bone marrow）中，影响正常血细胞（blood cells）的产生，并可能导致骨损伤（bone damage）**和其他严重健康问题</p>
<section id="背景" class="level2">
<h2 class="anchored" data-anchor-id="背景">背景</h2>
<section id="骨骼的主要功能key-functions-of-bones" class="level3">
<h3 class="anchored" data-anchor-id="骨骼的主要功能key-functions-of-bones">骨骼的主要功能（Key functions of bones）</h3>
<ol type="1">
<li>维持身体形态（Contribute to body’s shape and form）</li>
<li>支撑身体（Support the body）</li>
<li>保护重要器官（Protect vital organs）</li>
<li>实现身体运动（Enable body movement）</li>
<li>储存脂肪、成长因子和重要矿物质（Store fat, growth factors, and minerals）</li>
<li>作为大多数血细胞生成的场所（Act as site of most blood cell formation）</li>
</ol>
</section>
<section id="骨代谢bone-metabolism-和-骨重塑bone-remodeling" class="level3">
<h3 class="anchored" data-anchor-id="骨代谢bone-metabolism-和-骨重塑bone-remodeling">骨代谢（Bone metabolism） 和 骨重塑（Bone remodeling）</h3>
<ol type="1">
<li>骨代谢的本质
<ul>
<li>成年人骨代谢主要包括 骨重塑（remodeling） 和 修复（repair）。</li>
<li>骨骼不是静态的结构，而是持续更新的组织。</li>
</ul></li>
<li>骨重塑（Bone remodeling, 骨重塑）
<ul>
<li>骨重塑是旧骨组织被新骨组织不断替换的过程。</li>
<li>每周大约有 5% 的骨质量（bone mass）被更新。</li>
<li>涉及两个关键过程：
<ul>
<li>骨吸收（Bone resorption）：由破骨细胞（Osteoclasts）完成，分解旧骨。</li>
<li>骨形成（Bone deposition）：由成骨细胞（Osteoblasts）完成，沉积新骨。</li>
</ul></li>
</ul></li>
<li>生理平衡
<ul>
<li>在健康成年人中，骨吸收和骨形成的速率基本相等，维持骨量和骨强度的稳定。</li>
<li>成骨细胞与破骨细胞之间通过 生长因子（Growth factors） 等信号分子相互调控。</li>
</ul></li>
</ol>
</section>
<section id="骨组织-bone-tissue-与骨髓结构-bone-marrow" class="level3">
<h3 class="anchored" data-anchor-id="骨组织-bone-tissue-与骨髓结构-bone-marrow">骨组织 (Bone Tissue) 与骨髓结构 (Bone Marrow)</h3>
<ol type="1">
<li>红骨髓（Red Bone Marrow）</li>
</ol>
<ul>
<li>主要功能：造血（Hematopoiesis）。</li>
<li>是血细胞（包括红细胞、白细胞和血小板）的主要生成部位。</li>
<li>在儿童中普遍存在；随着年龄增长，一部分逐渐被黄骨髓取代。</li>
</ul>
<ol start="2" type="1">
<li>黄骨髓（Yellow Bone Marrow）</li>
</ol>
<ul>
<li>主要由脂肪细胞（fat cells）构成。</li>
<li>在特定条件下（如严重失血）可以重新转化为红骨髓以恢复造血功能。</li>
</ul>
<ol start="3" type="1">
<li>致密骨（Compact Bone）</li>
</ol>
<ul>
<li>坚硬、致密，构成骨骼的主要外层。</li>
<li>提供结构支撑与强度。</li>
</ul>
<ol start="4" type="1">
<li>松质骨（Spongy Bone）</li>
</ol>
<ul>
<li>内部呈网格状，含有大量骨髓腔隙。</li>
<li>有助于减轻骨骼重量并为骨髓提供空间。</li>
</ul>
</section>
<section id="造血-hematopoiesis" class="level3">
<h3 class="anchored" data-anchor-id="造血-hematopoiesis">造血 (Hematopoiesis)</h3>
<ol type="1">
<li>造血的本质</li>
</ol>
<ul>
<li>所有血细胞（红细胞、白细胞、血小板）都起源于同一种 多能造血干细胞。</li>
<li>这些干细胞主要位于 红骨髓（Red bone marrow）。</li>
</ul>
<ol start="2" type="1">
<li>多能造血干细胞（Pluripotent Hematopoietic Stem Cells）特点</li>
</ol>
<ul>
<li>未分化（Undifferentiated, 未分化）：属于前体干细胞。</li>
<li>分化潜能（Differentiation potential）：能够分化为所有血细胞类型。</li>
<li>自我更新（Self-renewal）：能够通过分裂保持自身数量。</li>
<li>调控依赖（Regulated by factors）：其自我更新和分化受到多种因子（如生长因子 growth factors 和细胞因子 cytokines）的调节。</li>
</ul>
<section id="造血分化过程" class="level4">
<h4 class="anchored" data-anchor-id="造血分化过程">造血分化过程</h4>
<ol type="1">
<li>血干细胞（Blood Stem Cell）</li>
</ol>
<ul>
<li>起源细胞，能够分化为所有血细胞类型。</li>
</ul>
<ol start="2" type="1">
<li>主要分化方向</li>
</ol>
<ul>
<li>红细胞（Red Blood Cells）：运输氧气和营养物质。</li>
<li>血小板（Platelets）：参与血液凝固，防止出血。</li>
<li>白细胞（White Blood Cells）：包括多种免疫细胞，如：
<ul>
<li>粒细胞（Granulocytes）：抵御感染。</li>
<li>自然杀伤细胞（Natural Killer Cell）：直接杀伤病毒感染细胞和肿瘤细胞。</li>
<li>B 细胞（B Cell）：可进一步分化为<em>浆细胞（Plasma Cell）</em>，产生抗体。</li>
<li>T 细胞（T Cell）：参与细胞免疫反应。</li>
</ul></li>
</ul>
<ol start="3" type="1">
<li>多发性骨髓瘤的异常</li>
</ol>
<ul>
<li>在 MM 中，B 细胞异常分化，导致浆细胞过度增殖。</li>
<li>过多的浆细胞不仅破坏骨髓微环境，还抑制正常血细胞的生成 → 造成贫血、免疫功能低下和出血倾向。</li>
</ul>
</section>
</section>
<section id="浆细胞与抗体功能plasma-cells-and-antibodies" class="level3">
<h3 class="anchored" data-anchor-id="浆细胞与抗体功能plasma-cells-and-antibodies">浆细胞与抗体功能（Plasma Cells and Antibodies）</h3>
<p>浆细胞来源于淋巴系干细胞（Lymphoid Stem Cells）。血液干细胞首先分化为淋巴系干细胞，随后进一步形成淋巴母细胞（Lymphoid Blast），再分化为 B 淋巴细胞（B Lymphocytes）、T 淋巴细胞（T Lymphocytes）和自然杀伤细胞（Natural Killer Cells）。其中 B 淋巴细胞能够进一步分化为浆细胞（Plasma Cells）。</p>
<ul>
<li>浆细胞的主要功能是产生抗体（Antibodies，也称免疫球蛋白 Immunoglobulins），用于识别和攻击特定病原体，如细菌或病毒。<br>
</li>
<li>抗体分子由两条重链（Heavy Chains，分为 A、D、G、E 或 M 类，决定抗体类型）和两条轻链（Light Chains）组成，整体呈 Y 形结构。<br>
</li>
<li>在正常情况下，浆细胞会产生多种不同类型的抗体，以维持免疫防御。<br>
</li>
<li>在多发性骨髓瘤中，恶性浆细胞会大量复制同一种抗体，称为 <strong>M 蛋白（M protein）</strong>。<br>
</li>
<li>这些异常单克隆抗体不仅缺乏正常免疫功能，还可能沉积在肾脏等器官中，引发器官损伤。</li>
</ul>
</section>
<section id="浆细胞肿瘤plasma-cell-neoplasms" class="level3">
<h3 class="anchored" data-anchor-id="浆细胞肿瘤plasma-cell-neoplasms">浆细胞肿瘤（Plasma Cell Neoplasms）</h3>
<p>浆细胞肿瘤是一类疾病，特点是体内产生异常浆细胞（称为骨髓瘤细胞 Myeloma Cells），这些细胞可以在骨骼或软组织中形成肿瘤。主要包括以下几种情况：</p>
<ul>
<li>不明意义单克隆免疫球蛋白病（Monoclonal Gammopathy of Undetermined Significance, MGUS）：骨髓中异常浆细胞比例 &lt;10%。MGUS 通常无症状，但在少部分患者中可进展为更严重的疾病，如淀粉样变（Amyloidosis）、多发性骨髓瘤（Multiple Myeloma）、淋巴瘤（Lymphoma）或慢性淋巴细胞白血病（Chronic Lymphocytic <a href="../../../docs/pharmaceutical/disease/Leukemia.html">Leukemia</a>）。</li>
<li>浆细胞瘤（Plasmacytoma）：在未受累部位的骨髓中异常浆细胞比例 &lt;10%，表现为骨或软组织的单一肿瘤。<br>
</li>
<li>多发性骨髓瘤（Multiple Myeloma, MM）：表现为多处骨骼中的肿瘤，是浆细胞肿瘤中最常见和最严重的类型。</li>
</ul>
</section>
</section>
<section id="发病机制pathogenesis" class="level2">
<h2 class="anchored" data-anchor-id="发病机制pathogenesis">发病机制（Pathogenesis）</h2>
<ul>
<li>multiple myeloma 通常起源于一种癌前阶段，即不明意义单克隆免疫球蛋白病（Monoclonal Gammopathy of Undetermined Significance, MGUS）。大约一半 MGUS 病例与免疫球蛋白重链（IgH）基因易位相关，另一部分则表现为染色体三倍体（Chromosomal Hyperdiploidy）。这些遗传学事件促进浆细胞（Plasma cells）的克隆性扩增，产生过量的单克隆免疫球蛋白，即 M 蛋白（M protein）。<br>
</li>
<li>次级遗传事件（Secondary genetic events）进一步推动 MGUS 以约 1%/年的速率进展为 multiple myeloma。<br>
</li>
<li>Myeloma cells 在骨髓中异常增殖，挤占正常造血细胞（Hematopoietic cells）的空间，导致红细胞、白细胞和血小板生成不足。<br>
</li>
<li>恶性浆细胞侵入骨组织，在全身多处形成肿瘤，并通过诱导血管生成（Angiogenesis）及细胞因子（如 IL-6）的旁分泌环路维持增殖。<br>
</li>
<li>骨代谢失衡：破骨细胞（Osteoclasts）活性异常增强，骨吸收（Bone resorption）超过骨形成（Bone formation），导致溶骨性病灶（Lytic bone lesions）。<br>
</li>
<li>过量 M protein 和游离轻链（Free light chains）在血液循环中积聚，并沉积于肾脏等器官，引起肾功能损伤。<br>
</li>
<li>临床上表现为典型的四大特征：贫血（Anemia）、高钙血症（Hypercalcemia）、溶骨性病变（Lytic bone lesions）、肾功能不全（Renal impairment）。</li>
</ul>
</section>
<section id="遗传学机制genetics" class="level2">
<h2 class="anchored" data-anchor-id="遗传学机制genetics">遗传学机制（Genetics）</h2>
<ul>
<li><p>multiple myeloma 的发生和进展与细胞遗传学异常密切相关，这些异常为肿瘤细胞提供了增殖优势。<br>
</p></li>
<li><p>根据 “two-hit genetic model of malignancy”，早期克隆性遗传事件驱动 MGUS 阶段，而次级遗传事件促进其向恶性转化。</p></li>
<li><p>在 MGUS 中，约一半病例携带免疫球蛋白重链（IgH）基因易位（Translocation），涉及常见的染色体异常：</p>
<ul>
<li>t(11;14)(q13;q32) → CCND1<br>
</li>
<li>t(4;14)(p16;q32) → FGFR3 和 MMSET<br>
</li>
<li>t(14;16)(q32;q23) → C-MAF<br>
</li>
<li>t(6;14)(p21;q32) → CCND3<br>
</li>
<li>t(14;20)(q32;q11) → MAFB<br>
</li>
</ul></li>
<li><p>另有约 50% 的 MGUS 表现为染色体数目异常增加（Hyperdiploidy），主要表现为奇数号染色体拷贝增加。</p></li>
<li><p>随着 MGUS 向 multiple myeloma 进展，常见的次级遗传学事件包括：</p>
<ul>
<li>染色体 13 的缺失（Deletion of chromosome 13），在多达 50% 的病例中出现。<br>
</li>
<li>RAS 突变（RAS mutations）。<br>
</li>
<li>p53 突变（p53 mutations）。<br>
</li>
<li>p16 甲基化（p16 methylation）。<br>
</li>
<li>MYC 基因异常（MYC abnormalities）。<br>
</li>
<li>17p 缺失（Del(17p)）。<br>
</li>
<li>其他次级染色体易位（Secondary translocations）。</li>
</ul></li>
</ul>
</section>
<section id="流行病学与趋势prevalence-and-trends" class="level2">
<h2 class="anchored" data-anchor-id="流行病学与趋势prevalence-and-trends">流行病学与趋势（Prevalence and Trends）</h2>
<ul>
<li>multiple myeloma 的终身风险约为 0.9%。<br>
</li>
<li>种族和性别是主要危险因素：在非裔人群中的发病率超过白人和西班牙裔的两倍，男性的发病率高于女性。<br>
</li>
<li>2017–2021 年间，不同人群的年发病率：
<ul>
<li>Non-Hispanic White: 8.1 per 100,000 men；5.1 per 100,000 women<br>
</li>
<li>Non-Hispanic Black: 17.1 per 100,000 men；13.0 per 100,000 women<br>
</li>
<li>Hispanic: 7.9 per 100,000 men；5.8 per 100,000 women</li>
</ul></li>
<li>multiple myeloma 多发生于老年人群，诊断时的中位年龄为 69 岁，死亡时的中位年龄为 76 岁。<br>
</li>
<li>预后与疾病分期相关：
<ul>
<li>Localized myeloma：5 年生存率约 80.3%。<br>
</li>
<li>Distant myeloma：5 年生存率下降至约 60.4%。</li>
</ul></li>
</ul>
</section>
<section id="临床表现与症状signs-and-symptoms" class="level2">
<h2 class="anchored" data-anchor-id="临床表现与症状signs-and-symptoms">临床表现与症状（Signs and Symptoms）</h2>
<ul>
<li><p>骨髓和骨骼损伤：progressive bone damage 是 multiple myeloma 的主要特征。近三分之二的患者以骨痛（Bone pain）为首发症状，常见于脊柱、骨盆、胸骨、肩胛骨及四肢长骨。骨质破坏导致溶骨性病灶（Lytic bone lesions），并增加骨折风险。部分患者会发生脊髓压迫（Spinal cord compression），表现为剧烈背痛、麻木及肌无力。<br>
</p></li>
<li><p>骨质疏松（Osteoporosis）在患者中常见，进一步增加病理性骨折的风险。</p></li>
<li><p>造血功能障碍：骨髓被大量 myeloma cells 占据后，正常造血受抑制，导致细胞减少症（Cytopenias）。</p>
<ul>
<li>贫血（Anemia）：引起疲劳、乏力、头晕。<br>
</li>
<li>白细胞减少（Leukopenia）：降低免疫防御力，增加感染风险。<br>
</li>
<li>血小板减少（Thrombocytopenia）：导致易出血、皮肤瘀斑。</li>
</ul></li>
<li><p>高钙血症（Hypercalcemia）：由于骨吸收增加，血钙水平升高，临床表现包括食欲减退、恶心、呕吐、便秘、多尿、口渴、意识混乱、乏力及昏迷。约 25–30% 的患者在诊断时即存在高钙血症，这是肾功能衰竭（Renal failure）的主要原因之一。</p></li>
<li><p>免疫功能异常：恶性浆细胞产生大量单克隆免疫球蛋白（M protein），但抑制了正常抗体的生成。结果表现为：</p>
<ul>
<li>感染易感性增加（Increased susceptibility to infections）。<br>
</li>
<li>反复呼吸道感染和泌尿道感染常见。</li>
</ul></li>
<li><p>器官损伤：</p>
<ul>
<li>肾损伤（Renal impairment）：M protein 和 free light chains 在肾脏沉积，导致肾小管损伤和肾衰竭。<br>
</li>
<li>血液黏稠度增加（Poor circulation）：M protein 过多导致血流缓慢，引起头晕、意识障碍、中风样表现，以及肾脏血流不足。</li>
</ul></li>
</ul>
</section>
<section id="diagnosis" class="level2">
<h2 class="anchored" data-anchor-id="diagnosis">Diagnosis</h2>
<section id="检测与诊断multiple-myeloma-testing" class="level3">
<h3 class="anchored" data-anchor-id="检测与诊断multiple-myeloma-testing">检测与诊断（Multiple Myeloma Testing）</h3>
<ul>
<li><p>病史采集和体格检查（Medical history and physical examination）：评估症状、体征及家族史，判断整体健康状况，并结合实验室检测结果进一步分析。<br>
</p></li>
<li><p>实验室检查（Laboratory tests）：包括血液学检测、血清学检测以及尿液分析（Urinalysis），用于评估 M protein、轻链和其他相关指标。<br>
</p></li>
<li><p>细胞遗传学检测（Cytogenetics testing）：检测染色体异常和基因改变，帮助确定预后风险。<br>
</p></li>
<li><p>骨髓穿刺与活检（Bone marrow aspiration and biopsy）：评估骨髓中 plasma cells 的比例和形态学特征，是确诊的重要手段。<br>
</p></li>
<li><p>荧光原位杂交（Plasma cell FISH, Fluorescence in situ hybridization）：用于检测特定基因易位或缺失。</p></li>
<li><p>影像学检查：</p>
<ul>
<li>CT 或 FDG-PET/CT：评估骨骼损伤及病灶分布。<br>
</li>
<li>全身 MRI（Whole-body MRI）：检测隐匿性骨病变和软组织受累。<br>
</li>
</ul></li>
<li><p>其他检测：</p>
<ul>
<li>血清黏度（Serum viscosity）：评估高黏滞综合征。<br>
</li>
<li>组织活检（Tissue biopsy）：用于怀疑孤立性浆细胞瘤（Plasmacytoma）的患者。<br>
</li>
<li>超声心动图（Echocardiogram）：评估心脏功能，特别是在怀疑淀粉样变性（Amyloidosis）时。</li>
</ul></li>
</ul>
</section>
<section id="crab-criteria-for-diagnosis" class="level3">
<h3 class="anchored" data-anchor-id="crab-criteria-for-diagnosis">CRAB Criteria for Diagnosis</h3>
<p>临床上，多发性骨髓瘤的诊断常参考 <strong>CRAB 标准</strong>，这是四个关键临床特征的首字母缩写：</p>
<ul>
<li><p><strong>C = Calcium elevation（高钙血症 / Hypercalcemia）</strong></p>
<ul>
<li>血清钙（serum calcium）升高 &gt; 11 mg/dL 或 &gt; 0.25 mmol/L 超过正常上限。</li>
</ul></li>
<li><p><strong>R = Renal dysfunction（肾功能受损 / Renal insufficiency）</strong></p>
<ul>
<li>血清肌酐（serum creatinine）升高 &gt; 2 mg/dL，或肾小球滤过率（eGFR）下降 &lt; 40 mL/min。</li>
</ul></li>
<li><p><strong>A = Anemia（贫血 / Anemia）</strong></p>
<ul>
<li>血红蛋白（hemoglobin）低于正常下限 ≥ 2 g/dL，或低于 10 g/dL。</li>
</ul></li>
<li><p><strong>B = Bone lesions（骨损伤 / Bone lesions）</strong></p>
<ul>
<li>影像学（X-ray, MRI, CT, PET-CT）显示一个或多个溶骨性病灶（lytic lesions）。</li>
</ul></li>
</ul>
<blockquote class="blockquote">
<p>⚠️ 说明：CRAB 标准常作为 <strong>治疗起点（indication for therapy）</strong> 的依据，因为它反映了器官损害（end-organ damage）的存在。</p>
</blockquote>
</section>
<section id="laboratory-tests" class="level3">
<h3 class="anchored" data-anchor-id="laboratory-tests">Laboratory Tests</h3>
<ul>
<li><strong>血液学检测（Hematology tests）</strong>
<ul>
<li>血常规（Complete blood count, CBC）：评估红细胞（Red blood cells）、白细胞（White blood cells）和血小板（Platelets）。贫血（Anemia）是 multiple myeloma 最常见的细胞减少症。</li>
</ul></li>
<li><strong>血液化学检测（Blood chemistry panel）</strong>
<ul>
<li>血尿素氮和肌酐（BUN and Creatinine）：反映肾功能。<br>
</li>
<li>白蛋白（Albumin）：在晚期 multiple myeloma 患者中常降低。<br>
</li>
<li>钙（Calcium）：常升高，提示骨破坏和高钙血症（Hypercalcemia）。<br>
</li>
<li>其他指标：乳酸脱氢酶（LDH）、β2 微球蛋白（Beta-2 microglobulin），均为常用预后因子。</li>
</ul></li>
<li><strong>定量免疫球蛋白（Serum quantitative immunoglobulins）</strong>
<ul>
<li>正常情况下，浆细胞可产生 IgA、IgD、IgE、IgG、IgM 五类免疫球蛋白。<br>
</li>
<li>在 multiple myeloma 中，恶性浆细胞通常只产生单一类型免疫球蛋白，即 M 蛋白（M protein）。</li>
</ul></li>
<li><strong>血液和尿液电泳（Blood and urine electrophoresis）</strong>
<ul>
<li>血清蛋白电泳（SPEP, Serum protein electrophoresis）：检测血清中免疫球蛋白含量。<br>
</li>
<li>血清免疫固定电泳（SIFE, Serum immunofixation electrophoresis）：确定抗体类别（如 IgG）。<br>
</li>
<li>尿蛋白电泳（UPEP, Urine protein electrophoresis）和尿免疫固定电泳（UIFE, Urine immunofixation electrophoresis）：通常在 24 小时尿液样本中进行，用于检测 Bence Jones 蛋白（轻链）。</li>
</ul></li>
<li><strong>游离轻链检测（Free light chain assay）</strong>
<ul>
<li>定量检测血液中游离轻链的水平。<br>
</li>
<li>在 SPEP 未能发现 M 蛋白时，尤其适用于识别特殊亚型 multiple myeloma。</li>
</ul></li>
<li><strong>血清黏度（Serum viscosity test）</strong>
<ul>
<li>在怀疑高黏滞综合征时使用，反映血液黏稠度。</li>
</ul></li>
<li><strong>浆细胞标记指数（Plasma cell labeling index）</strong>
<ul>
<li>评估浆细胞群体中处于分裂状态的比例，反映细胞增殖速度。</li>
</ul></li>
</ul>
</section>
<section id="活检biopsies" class="level3">
<h3 class="anchored" data-anchor-id="活检biopsies">活检（Biopsies）</h3>
<ul>
<li><p>骨髓穿刺与活检（Bone marrow aspiration and biopsy）：常在髂后嵴进行，局部麻醉后插入针头抽取少量液体骨髓，同时取骨和骨髓小块进行检查。通过显微镜评估细胞形态、数量及排列，并在检测到 multiple myeloma 时定量恶性细胞比例。</p></li>
<li><p>骨髓分析（Bone marrow analysis）：</p>
<ul>
<li>免疫组织化学（Immunohistochemistry）：利用抗体检测特定细胞表面分子，区分 myeloma cells 与其他细胞。<br>
</li>
<li>流式细胞术（Flow cytometry）：通过免疫表型（Immunophenotyping）识别浆细胞的特定表面标记。</li>
<li>细胞遗传学（Cytogenetic analysis）：评估骨髓细胞和 myeloma cells 的染色体数目异常和易位/缺失。<br>
</li>
<li>荧光原位杂交（Fluorescence in situ hybridization, FISH）：利用荧光探针检测染色体异常。<br>
</li>
<li>淀粉样变性评估（Evaluation of light chain amyloidosis）：检测异常折叠轻链沉积形成的淀粉样蛋白。</li>
</ul></li>
<li><p>活检结果不仅用于确诊 multiple myeloma，还能提供预后信息，并指导治疗方案选择。</p></li>
</ul>
</section>
<section id="imaging-tests" class="level3">
<h3 class="anchored" data-anchor-id="imaging-tests">Imaging Tests</h3>
<ul>
<li><p>影像学检查用于观察骨髓瘤对骨骼和器官的损害程度，方法包括超声（Ultrasound）、X 线（X-ray）、磁共振（MRI）、CT 及 PET 扫描。</p></li>
<li><p>骨调查（Bone survey）：常规 X 线用于检测骨质破坏，帮助评估哪些骨骼受累以及损伤范围。<br>
</p></li>
<li><p>CT（Computed tomography）：通过 X 线生成横断面影像，提供更精细的骨结构及器官切片信息，有助于评估骨损害的范围。<br>
</p></li>
<li><p>MRI（Magnetic resonance imaging）：利用磁场和射频波成像，适用于显示骨骼、脊髓及骨髓受累情况，对隐匿性骨损害敏感。<br>
</p></li>
<li><p>PET/CT（Positron emission tomography combined with CT）：通过注射放射性示踪剂定位肿瘤细胞，可检测常规 X 线未能发现的浆细胞瘤（Plasmacytomas）。</p></li>
<li><p>这些影像学工具不仅有助于确诊 multiple myeloma，还能监测病情进展和疗效反应。</p></li>
</ul>
</section>
<section id="诊断标准establishing-the-diagnosis" class="level3">
<h3 class="anchored" data-anchor-id="诊断标准establishing-the-diagnosis">诊断标准（Establishing the Diagnosis）</h3>
<p>multiple myeloma 的诊断依赖病史、体格检查、实验室检测、骨髓活检及影像学结果的综合判断。根据 American Cancer Society 的标准：</p>
<ul>
<li>符合以下任一条件即可确诊：
<ul>
<li>骨髓瘤瘤块（Plasma cell tumor），通过活检（Biopsy）证实。<br>
</li>
<li>骨髓中 plasma cells ≥10%，并伴随以下至少一项：
<ul>
<li>高钙血症（High blood calcium）<br>
</li>
<li>肾功能不全（Poor kidney function）<br>
</li>
<li>贫血（Anemia）<br>
</li>
<li>影像学发现骨质破坏（Holes in bones from tumor growth）<br>
</li>
<li>单一类型轻链（Light chain）水平较另一类型高 100 倍<br>
</li>
<li>骨髓中 plasma cells ≥60%</li>
</ul></li>
</ul></li>
<li>Smoldering myeloma（惰性骨髓瘤）：属于早期恶性阶段，无明显症状或器官损伤。
<ul>
<li>血常规、血钙和肾功能多为正常<br>
</li>
<li>不伴随骨破坏或器官损伤<br>
</li>
<li>无淀粉样变性（Amyloidosis）迹象</li>
</ul></li>
</ul>
</section>
</section>
<section id="other-disease-information" class="level2">
<h2 class="anchored" data-anchor-id="other-disease-information">Other Disease Information</h2>
<section id="imwg-frailty-score" class="level3">
<h3 class="anchored" data-anchor-id="imwg-frailty-score">IMWG Frailty Score</h3>
<p>这是 International Myeloma Working Group（IMWG） 在 2015 年开发的一项评估工具，目的是量化多发性骨髓瘤患者整体的“身体脆弱性”，帮助医生在制定治疗方案时权衡疗效与风险。其目标是合理区分不同体质老年患者，以便调整治疗强度与方式</p>
<p>该 frailty score 是基于三个维度的简单加权评分模型：</p>
<ol type="1">
<li><p>年龄（Age）</p></li>
<li><p>日常生活活动能力（Activities of Daily Living, ADL）</p></li>
<li><p>工具性日常生活能力（Instrumental ADL, IADL）</p></li>
<li><p>合并症指数（Comorbidities via <strong>Charlson Comorbidity Index</strong>, CCI）</p>
<div class="callout callout-style-default callout-note callout-titled" title="Charlson Comorbidity Index">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Charlson Comorbidity Index
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Charlson Comorbidity Index 是一种 合并症评估工具（comorbidity assessment tool），由 Charlson 等人在 1987 年提出，用于通过量化患者的合并疾病情况，预测 10 年死亡风险（10-year mortality risk）。</p>
<p>CCI 包含 19 种合并症（comorbid conditions），每种疾病赋予不同权重（1, 2, 3, 或 6 分），然后累加得出总分。</p>
<p>1 分（1 point）</p>
<pre><code>- 心肌梗死（Myocardial infarction）
- 充血性心力衰竭（Congestive heart failure）
- 外周血管疾病（Peripheral vascular disease）
- 脑血管疾病（Cerebrovascular disease）
- 痴呆（Dementia）
- 慢性肺病（Chronic pulmonary disease, e.g. COPD）
- 结缔组织病（Connective tissue disease, e.g. rheumatoid arthritis）
- 消化性溃疡病（Peptic ulcer disease）
- 轻度肝病（Mild liver disease）
- 糖尿病（Diabetes mellitus, uncomplicated）</code></pre>
<p>2 分（2 points）</p>
<pre><code>- 糖尿病伴终末器官损害（Diabetes with end-organ damage）
- 偏瘫（Hemiplegia or paraplegia）
- 肾功能不全（Moderate or severe renal disease）
- 肿瘤（Any solid tumor, without metastasis）
- 白血病（Leukemia）
- 恶性淋巴瘤（Lymphoma）</code></pre>
<p>3 分（3 points）</p>
<pre><code>- 中度或重度肝病（Moderate or severe liver disease）</code></pre>
<p>6 分（6 points）</p>
<pre><code>- 转移性实体瘤（Metastatic solid tumor）
- 获得性免疫缺陷综合征（AIDS/HIV）</code></pre>
<p>评分与解释（Scoring &amp; Interpretation）</p>
<pre><code>- 总分（Total Score） = 各合并症得分累加
- 分值越高 → 死亡风险越高，预后越差</code></pre>
<p>👉 原始研究中，Charlson 等人为每个得分对应了一个 10 年死亡率估计值：</p>
<pre><code>- 0 分：~12%
- 1–2 分：~26%
- 3–4 分：~52%
- ≥5 分：~85%</code></pre>
</div>
</div>
</div></li>
</ol>
<p>打分标准（Scoring System）</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>评分要素 (Factor)</strong></th>
<th><strong>分值 (Score)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>年龄 Age</strong></td>
<td>≤75 岁 = 0 分；76–80 岁 = 1 分；&gt;80 岁 = 2 分</td>
</tr>
<tr class="even">
<td><strong>日常生活活动能力（ADL）</strong></td>
<td>≥4 分 = 0 分；&lt;4 分 = 1 分</td>
</tr>
<tr class="odd">
<td><strong>工具性日常生活活动能力（IADL）</strong></td>
<td>≥5 分 = 0 分；&lt;5 分 = 1 分</td>
</tr>
<tr class="even">
<td><strong>Charlson 合并症指数（CCI）</strong></td>
<td>0 = 0 分；≥1 = 1 分</td>
</tr>
</tbody>
</table>
<p>通过上述指标的累加得分，IMWG 衰弱评分可将 MM 患者分为三个体质类别：</p>
<ul>
<li>Fit（适合）</li>
<li>Intermediate-fit（中等体能）</li>
<li>Frail（衰弱）</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 33%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th><strong>总分 (Total Score)</strong></th>
<th><strong>分组 (Category)</strong></th>
<th><strong>含义 (Interpretation)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><strong>Fit（健康）</strong></td>
<td>体能良好，可耐受强度治疗</td>
</tr>
<tr class="even">
<td>1</td>
<td><strong>Intermediate-fit（中等体能）</strong></td>
<td>适度衰弱，需要权衡治疗强度</td>
</tr>
<tr class="odd">
<td>≥2</td>
<td><strong>Frail（衰弱）</strong></td>
<td>脆弱患者，更高毒性风险，需减量或温和治疗</td>
</tr>
</tbody>
</table>
<p>这三个分组在统计分析中具有显著差异：</p>
<ul>
<li>3年整体生存率（3-year OS）：Fit ~84%，Intermediate ~76%，Frail ~57%</li>
<li>≥3 级非血液毒性不良事件发生率（Grade ≥3 non-hematologic AEs）（1年内）：Fit ~22.2%，Intermediate ~26.4%，Frail ~34.0%</li>
<li>12个月治疗中断率（Treatment discontinuation）：Fit ~16.5%，Intermediate ~20.8%，Frail ~31.2%</li>
</ul>
<p>这说明 IMWG frailty score 在预测患者 预后（OS） 和 治疗耐受性／毒性风险 方面具有临床价值。</p>
</section>
<section id="common-baseline-requirement" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="common-baseline-requirement">Common Baseline Requirement</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 21%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><strong>指标</strong></th>
<th><strong>单位</strong></th>
<th><strong>正常参考范围</strong></th>
<th><strong>MM 患者常见情况</strong></th>
<th><strong>临床试验常见入组标准</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Corrected Serum Calcium</strong></td>
<td>mmol/L</td>
<td>2.1 – 2.6</td>
<td>常见 <strong>高钙血症 &gt; 2.75</strong>（CRAB 特征之一）</td>
<td>一般要求 ≤ 3.0，严重高钙需处理后再入组</td>
</tr>
<tr class="even">
<td><strong>Hemoglobin</strong></td>
<td>g/L</td>
<td>男 135–175女 120–160</td>
<td>常见 <strong>&lt; 100 g/L</strong>，贫血</td>
<td>一般要求 ≥ 80–90</td>
</tr>
<tr class="odd">
<td><strong>Platelets</strong></td>
<td>×10⁹/L</td>
<td>150–400</td>
<td>可见降低，有时 &lt; 100</td>
<td>≥ 75–100</td>
</tr>
<tr class="even">
<td><strong>Neutrophils (ANC)</strong></td>
<td>×10⁹/L</td>
<td>1.5–8.0</td>
<td>骨髓受累可低于 1.5</td>
<td>≥ 1.0–1.5</td>
</tr>
<tr class="odd">
<td><strong>Serum Creatinine</strong></td>
<td>µmol/L</td>
<td>男 62–115女 53–97</td>
<td>肾损伤常见 &gt; 177 (≈2 mg/dL)</td>
<td>CrCl ≥ 30–50 mL/min 或 Scr ≤ 177</td>
</tr>
<tr class="even">
<td><strong>% Plasma Cell (BM)</strong></td>
<td>%</td>
<td>&lt; 5</td>
<td>诊断标准之一：≥10%</td>
<td>多数要求 ≥10 才确诊，可作为疾病负荷基线</td>
</tr>
<tr class="odd">
<td><strong>Albumin</strong></td>
<td>g/dL</td>
<td>3.5 – 5.0</td>
<td>常见 &lt; 3.5</td>
<td>ISS 分期 cut-off：3.5</td>
</tr>
<tr class="even">
<td><strong>β2-Microglobulin</strong></td>
<td>mg/L</td>
<td>≤ 2.5</td>
<td>&gt; 3.5（ISS II/III 分期）</td>
<td>仅描述预后分层，无硬性入组限制</td>
</tr>
<tr class="odd">
<td><strong>LDH</strong></td>
<td>U/L</td>
<td>~100 – 250</td>
<td>升高提示疾病侵袭性强</td>
<td>R-ISS 分期指标</td>
</tr>
<tr class="even">
<td><strong>Cytogenetic Abnormality</strong></td>
<td>—</td>
<td>正常核型</td>
<td>高危异常包括 del(17p)、t(4;14)、t(14;16)</td>
<td>R-ISS 高危分层</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Calcium ≥2.75 mmol/L (11 mg/dL)</strong>、<strong>Hb &lt;100 g/L</strong>、<strong>Cr &gt;177 µmol/L</strong>、<strong>≥10% plasma cells</strong> 等属于 IMWG 诊断和 CRAB 特征的一部分。</li>
<li><strong>入组标准</strong>更多是安全性考虑（避免严重贫血、中性粒细胞过低、血小板过低或肾功能严重受损）。</li>
<li><strong>β2-微球蛋白和白蛋白</strong>主要用于 <strong>ISS 分期</strong>，不作为硬性入组门槛，但非常重要的基线指标。</li>
</ul>
</section>
<section id="issinternational-staging-system-国际分期系统2005-年提出" class="level3">
<h3 class="anchored" data-anchor-id="issinternational-staging-system-国际分期系统2005-年提出">ISS（International Staging System, 国际分期系统，2005 年提出）</h3>
<p>ISS 仅基于两个血清学指标：</p>
<ul>
<li>β2-microglobulin (β2M, β2 微球蛋白)
<ul>
<li>一种小分子蛋白，存在于多数有核细胞表面，尤其是淋巴细胞。</li>
<li>主要经 肾脏清除。</li>
<li>在 MM 中：
<ul>
<li>反映 肿瘤负荷（浆细胞分泌越多，β2M 越高）。</li>
<li>也受肾功能影响（肾功能差时水平会升高）。</li>
</ul></li>
<li>正常值：≤ 2.5 mg/L。</li>
<li>预后(prognosis) 意义：越高，疾病负荷越大，预后越差。</li>
</ul></li>
<li>Albumin (ALB, 白蛋白)
<ul>
<li>由肝脏合成的主要血浆蛋白。</li>
<li>在 MM 中：
<ul>
<li>不是直接反映肿瘤负荷，而是间接反映 IL-6 水平（一种促炎细胞因子，会抑制白蛋白合成，同时促进浆细胞增殖）。</li>
</ul></li>
<li>ALB 越低，提示疾病更活跃、预后更差。</li>
<li>正常值：3.5 – 5.0 g/dL。</li>
<li>预后意义：低于 3.5 g/dL 时，提示疾病风险较高。</li>
</ul></li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>分期</strong></th>
<th><strong>判定标准</strong></th>
<th><strong>临床意义</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>ISS I</strong></td>
<td>β2M &lt; 3.5 mg/L 且 ALB ≥ 3.5 g/dL</td>
<td>预后最好</td>
</tr>
<tr class="even">
<td><strong>ISS II</strong></td>
<td>介于 I 和 III 之间</td>
<td>中等</td>
</tr>
<tr class="odd">
<td><strong>ISS III</strong></td>
<td>β2M ≥ 5.5 mg/L</td>
<td>预后最差</td>
</tr>
</tbody>
</table>
<p>📌 局限性：只考虑了肿瘤负荷指标（β2M、白蛋白），未包含遗传学和 LDH 等高危因素。</p>
</section>
<section id="r-issrevised-iss修订版国际分期系统2015-年提出" class="level3">
<h3 class="anchored" data-anchor-id="r-issrevised-iss修订版国际分期系统2015-年提出">R-ISS（Revised ISS，修订版国际分期系统，2015 年提出）</h3>
<p>R-ISS 在 ISS 的基础上，加入了 LDH 和细胞遗传学（FISH 检测的高危异常）：</p>
<ul>
<li>高危染色体异常包括：t(4;14)、t(14;16)、del(17p)。</li>
<li>LDH (Lactate Dehydrogenase, 乳酸脱氢酶)
<ul>
<li>正常范围：大约 100–250 U/L（不同实验室略有差异）。
<ul>
<li>为什么重要：
<ul>
<li>当细胞受到损伤或快速增殖时，LDH 会释放到血液中 → 水平升高。</li>
<li>在血液肿瘤（包括多发性骨髓瘤）中，LDH 升高通常提示：
<ul>
<li>肿瘤生长更快、代谢更活跃</li>
<li>预后更差</li>
<li>在 MM 中的应用：
<ul>
<li>在 R-ISS 分期里，LDH 被纳入预后评估：</li>
<li>如果 LDH 升高（超过实验室正常上限），就说明疾病更具侵袭性。</li>
<li>例如：ISS III + 高 LDH → 自动分到 R-ISS III（高危）。</li>
</ul></li>
</ul></li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 60%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th><strong>分期</strong></th>
<th><strong>判定标准</strong></th>
<th><strong>临床意义</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>R-ISS I</strong></td>
<td>ISS I 且 LDH 正常 且 无高危染色体异常</td>
<td>预后最好</td>
</tr>
<tr class="even">
<td><strong>R-ISS II</strong></td>
<td>不符合 I 或 III 的情况</td>
<td>中等</td>
</tr>
<tr class="odd">
<td><strong>R-ISS III</strong></td>
<td>ISS III 且 (LDH 升高 或 存在高危染色体异常)</td>
<td>预后最差</td>
</tr>
</tbody>
</table>
<p>📌 与 ISS 相比，R-ISS 更好地识别出一部分 ISS II 的高危患者，分层能力更强。</p>
</section>
<section id="type-of-heavy-chain-and-light-chain" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="type-of-heavy-chain-and-light-chain">Type of Heavy Chain and Light Chain</h3>
<p>抗体（免疫球蛋白, Ig）是由 两条重链 (heavy chains) 和 两条轻链 (light chains) 组成的。</p>
<ul>
<li>重链类型决定了抗体的种类(class): IgG, IgA, IgM, IgD, IgE
<ul>
<li>最常见的是 IgG 型 (约 50–60%)</li>
<li>其次是 IgA 型 (约 20–30%)</li>
<li>其他类型（IgM、IgD、IgE）比较罕见</li>
</ul></li>
<li>每个抗体分子除了重链，还会有一对轻链，分为：κ (kappa), λ (lambda)
<ul>
<li>浆细胞可能只分泌一种轻链 → 出现 游离轻链 (Free Light Chain, FLC) 增高</li>
<li>如果病人只有轻链，没有完整的免疫球蛋白，就叫 轻链型 MM (Light chain MM, ~15–20%)</li>
</ul></li>
</ul>
<p>合在一起，就能定义多发性骨髓瘤的亚型，例如 IgG κ型 MM、IgA λ型 MM、轻链 κ型 MM。</p>
<p>临床意义: + 诊断：通过 血清/尿蛋白电泳 (SPEP/UPEP) + 免疫固定电泳 (IFE) 来鉴定是哪种 Ig 类型（IgG/IgA 等 + κ/λ）。 + 监测疾病：随访时监测 M 蛋白水平 或 FLC 比值 (κ/λ)，用来判断疗效和复发。 + 预后：不同类型预后略有差异，比如 IgA 型通常病情进展比 IgG 型更快。</p>
<p>在多发性骨髓瘤 (MM) 中的抗体 - 异常克隆浆细胞 会不受控制地增殖，只分泌一种 单一类型的抗体或轻链，叫做 单克隆蛋白（M 蛋白，Monoclonal protein）。 - 这个 M 蛋白 失去了正常抗体的免疫功能，反而会： - 没有正常免疫作用（不能有效对抗病原体） - 在血液或尿液中积聚，导致 血液粘稠、肾脏损伤 - 取代正常免疫球蛋白的合成 → 免疫力下降 → 容易感染</p>
</section>
<section id="extramedullary-plasmacytomas-emps骨髓外浆细胞瘤" class="level3">
<h3 class="anchored" data-anchor-id="extramedullary-plasmacytomas-emps骨髓外浆细胞瘤">Extramedullary Plasmacytomas (EMPs，骨髓外浆细胞瘤)</h3>
<ul>
<li>浆细胞瘤（Plasmacytoma）：由单克隆浆细胞（monoclonal plasma cells）构成的肿瘤。</li>
<li>骨髓外浆细胞瘤（Extramedullary Plasmacytoma, EMP）：指浆细胞瘤发生在骨髓以外的组织或器官（outside the bone marrow），不依附于骨或骨髓。
<ul>
<li>Extraosseous EMP（真正的骨髓外浆细胞瘤）：浆细胞瘤完全位于 骨髓和骨之外的软组织/器官，没有与骨病灶相连。</li>
<li>Paraosseous EMP（邻骨性浆细胞瘤）：浆细胞瘤起源于 骨髓内，但肿瘤突破骨皮质向外生长，形成在骨外可见的肿块。</li>
</ul></li>
</ul>
<p>也可按是否伴随 MM 来分</p>
<ol type="1">
<li>孤立性骨髓外浆细胞瘤（Solitary EMP）</li>
</ol>
<ul>
<li>单一部位肿瘤，没有全身性多发性骨髓瘤（MM）的证据
<ul>
<li>占浆细胞肿瘤的 3–5% 左右</li>
</ul></li>
</ul>
<ol start="2" type="1">
<li>继发性 EMP（Secondary EMP in MM）
<ul>
<li>发生在多发性骨髓瘤患者中，作为疾病进展的一部分</li>
<li>与预后不良相关</li>
</ul></li>
</ol>
</section>
</section>
<section id="治疗" class="level2">
<h2 class="anchored" data-anchor-id="治疗">治疗</h2>
<p>Multiple Myeloma目前尚无法根治，治疗目标为缓解症状、延缓进展、延长生存（control symptoms, delay progression, prolong survival）。主要治疗方式：</p>
<ul>
<li><p>化疗 (Chemotherapy)</p></li>
<li><p>靶向治疗 (Targeted Therapy)</p>
<div class="callout callout-style-default callout-note callout-titled" title="Targets for MM">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Targets for MM
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>✅ 已经确立并应用在临床的靶点 （这些靶点已经有获批药物，并成为 MM 治疗标准的一部分）</p>
<ul>
<li>蛋白酶体（Proteasome） → Bortezomib, <a href="../../../docs/pharmaceutical/compound/Carfilzomib.html">Carfilzomib</a>, Ixazomib</li>
<li>Cereblon（CRBN）/ IMiD 通路 → <a href="../../../docs/pharmaceutical/compound/Thalidomide.html">Thalidomide</a>, Lenalidomide, Pomalidomide, Iberdomide/Mezigdomide（新一代 CELMoDs）</li>
<li>CD38 → Daratumumab, Isatuximab • SLAMF7（CS1） → Elotuzumab</li>
</ul>
<p>🚀 新一代免疫靶点（已获批或处于临床后期）</p>
<ul>
<li>BCMA（B-cell Maturation Antigen, B细胞成熟抗原）
<ul>
<li>CAR-T：Abecma, <a href="../../../docs/pharmaceutical/compound/Carvykti.html">Carvykti</a></li>
<li>双抗：Teclistamab, Elranatamab</li>
<li><a href="../../../docs/pharmaceutical/other/ADC.html">ADC</a>：Belantamab Mafodotin（部分市场退出，但研究继续）</li>
</ul></li>
<li>GPRC5D → Talquetamab（双抗），多款 <a href="../../../docs/pharmaceutical/other/CAR-T.html">CAR-T</a> 在研</li>
<li>FcRH5 → Cevostamab（双抗，研发中）</li>
</ul>
<p>🔬 仍在探索中的次要或联合靶点</p>
<ul>
<li>VEGF/VEGFR → Bevacizumab（骨髓瘤中单药疗效有限，多用于探索性研究）</li>
<li>RAS/MAPK 通路、BCL-2（如 Venetoclax 在 t(11;14) 亚群） → 针对分子亚型的精准治疗方向</li>
</ul>
</div>
</div>
</div></li>
<li><p>生物疗法 (Biological Therapy)</p></li>
<li><p>放疗 (Radiotherapy)</p></li>
<li><p>干细胞移植 (Stem Cell Transplant)</p></li>
</ul>
<section id="一线治疗frontline-newly-diagnosed" class="level3">
<h3 class="anchored" data-anchor-id="一线治疗frontline-newly-diagnosed">一线治疗（Frontline / Newly Diagnosed）</h3>
<ul>
<li>移植适合（Transplant-eligible）患者
<ul>
<li>三药方案 VRd（<a href="../../../docs/pharmaceutical/compound/Bortezomib.html">Bortezomib</a> + <a href="../../../docs/pharmaceutical/compound/Revlimid.html">Lenalidomide</a> + Dexamethasone）</li>
<li>四药方案 (Dara-VRd, <a href="../../../docs/pharmaceutical/compound/Darzalex.html">Daratumumab</a> 达雷妥尤单抗 + VRd），或 Isa-VRd（Isatuximab 异基妥昔单抗 + VRd），用于提升深度缓解（深度：MRD-neg 等）</li>
</ul></li>
<li>移植不适合（Transplant-ineligible）患者
<ul>
<li>常用方案如 D-Rd（Daratumumab + Lenalidomide + Dexamethasone）或 D-VMP（Daratumumab + <a href="../../../docs/pharmaceutical/compound/Bortezomib.html">Bortezomib</a> + Melphalan + Prednisone）</li>
</ul></li>
</ul>
</section>
<section id="二线治疗relapsed-refractory-mm-second-line" class="level3">
<h3 class="anchored" data-anchor-id="二线治疗relapsed-refractory-mm-second-line">二线治疗（Relapsed / Refractory MM, Second Line）</h3>
<ul>
<li>DVd = Daratumumab + Bortezomib + Dexamethasone
<ul>
<li>关键证据：CASTOR III期研究显示，与 Vd 相比，<a href="../../../docs/pharmaceutical/other/PFS.html">PFS</a> 显著延长、ORR 更高；后续更新报告 OS 获益趋势/结果支持DVd作为复发后标准方案之一。指南将 DVd 列为复发早期优选/Category 1 方案之一</li>
</ul></li>
<li>其他常用三药：
<ul>
<li>D-Rd（Daratumumab + Lenalidomide + Dex）</li>
<li>D-Kd（Daratumumab + <a href="../../../docs/pharmaceutical/compound/Carfilzomib.html">Carfilzomib</a> + Dex）</li>
<li>Kd（Carfilzomib + Dex）等；选择依据<strong>既往用药史（特别是是否对来那度胺耐药）</strong>与患者合并症。</li>
</ul></li>
<li>对于早复发/高危复发患者，可酌情评估 CAR-T（如 Cilta-cel、Ide-cel）或转入临床试验通道</li>
</ul>
</section>
<section id="三线治疗third-line" class="level3">
<h3 class="anchored" data-anchor-id="三线治疗third-line">三线治疗（Third Line）</h3>
<p>常见的方案包括：</p>
<ul>
<li>Daratumumab + Pomalidomide + Dex（D-Pd）</li>
<li>或继续使用 Daratumumab + Rd</li>
<li>同样，CAR-T 或 BCMA 导向治疗（如 Belantamab Mafodotin）也可考虑，具体取决于先前治疗史</li>
</ul>
</section>
<section id="四线及之后治疗fourth-line-and-beyond" class="level3">
<h3 class="anchored" data-anchor-id="四线及之后治疗fourth-line-and-beyond">四线及之后治疗（Fourth Line and Beyond）</h3>
<ul>
<li>BCMA (B-cell maturation antigen) 定向疗法（后期可选方案）：</li>
<li>已批准的双特异性抗体（bispecifics）：Teclistamab（<a href="../../../docs/pharmaceutical/compound/Tecvayli.html">Tecvayli</a>）、Talquetamab（Talvey）、Elranatamab（Elrexfio）</li>
<li>CAR-T 细胞疗法：如 Idecabtagene vicleucel（<a href="../../../docs/pharmaceutical/compound/Abecma.html">Abecma</a>）、Ciltacabtagene autoleucel（Carvykti），适用于至少一线或多线治疗失败后的患者</li>
<li>抗 BCMA ADC（抗体–药物偶联）：例如 Belantamab Mafodotin 已在 NHS 英格兰获批使用，用于四线或以上患者</li>
</ul>
<blockquote class="blockquote">
<p>BCMA的作用:</p>
<ul>
<li>主要表达在 B 细胞晚期分化阶段（浆细胞、部分浆细胞前体）。</li>
<li>作用是帮助 B 细胞成熟为浆细胞，维持其 长期存活。</li>
<li>与配体 BAFF（B-cell activating factor） 和 APRIL 结合后，促进 浆细胞存活、抗体分泌。</li>
</ul>
</blockquote>
</section>
<section id="therapy-for-previously-treated-multiple-myeloma" class="level3">
<h3 class="anchored" data-anchor-id="therapy-for-previously-treated-multiple-myeloma">Therapy for Previously Treated Multiple Myeloma</h3>
<ul>
<li><strong>适用情况</strong>
<ul>
<li>患者在同种异体或自体 stem cell transplantation 后复发 (relapsed disease)<br>
</li>
<li>患者在初始同种异体或自体 stem cell transplantation 后出现原发进展 (primary progressive disease)<br>
</li>
<li>不适合进行 stem cell transplantation 的患者，在初始治疗 (primary therapy) 后出现疾病进展或复发</li>
</ul></li>
</ul>
<section id="早期复发-early-relapse-13-次既往治疗" class="level4">
<h4 class="anchored" data-anchor-id="早期复发-early-relapse-13-次既往治疗">早期复发 (Early Relapse, 1–3 次既往治疗)</h4>
<ul>
<li>可重复初始诱导治疗 (primary induction therapy)，若复发发生在治疗后 &gt;6 个月</li>
</ul>
</section>
<section id="bortezomib-耐药的推荐方案-bortezomib-refractory-disease" class="level4">
<h4 class="anchored" data-anchor-id="bortezomib-耐药的推荐方案-bortezomib-refractory-disease">Bortezomib 耐药的推荐方案 (Bortezomib-Refractory Disease)</h4>
<ul>
<li>Daratumumab + lenalidomide + dexamethasone<br>
</li>
<li>Daratumumab + carfilzomib + dexamethasone<br>
</li>
<li>Carfilzomib + lenalidomide + dexamethasone<br>
</li>
<li>Carfilzomib + pomalidomide + dexamethasone<br>
</li>
<li>Isatuximab-irfc + carfilzomib + dexamethasone</li>
</ul>
</section>
<section id="lenalidomide-耐药的推荐方案-lenalidomide-refractory-disease" class="level4">
<h4 class="anchored" data-anchor-id="lenalidomide-耐药的推荐方案-lenalidomide-refractory-disease">Lenalidomide 耐药的推荐方案 (Lenalidomide-Refractory Disease)</h4>
<ul>
<li>Daratumumab + carfilzomib + dexamethasone<br>
</li>
<li>Daratumumab + bortezomib + dexamethasone<br>
</li>
<li>Isatuximab-irfc + carfilzomib + dexamethasone<br>
</li>
<li>Pomalidomide + bortezomib + dexamethasone<br>
</li>
<li>Selinexor + bortezomib + dexamethasone</li>
</ul>
</section>
<section id="其他推荐方案早期复发-other-recommended-regimens-for-early-relapses-13-次既往治疗" class="level4">
<h4 class="anchored" data-anchor-id="其他推荐方案早期复发-other-recommended-regimens-for-early-relapses-13-次既往治疗">其他推荐方案：早期复发 (Other Recommended Regimens for Early Relapses, 1–3 次既往治疗)</h4>
<ul>
<li>Bortezomib + cyclophosphamide + dexamethasone<br>
</li>
<li>Bortezomib + lenalidomide + dexamethasone<br>
</li>
<li>Carfilzomib（每周两次给药, twice weekly）+ dexamethasone<br>
</li>
<li>Elotuzumab + lenalidomide + dexamethasone<br>
</li>
<li>Carfilzomib + cyclophosphamide + dexamethasone<br>
</li>
<li>Cyclophosphamide + lenalidomide + dexamethasone<br>
</li>
<li>Daratumumab + cyclophosphamide + bortezomib + dexamethasone<br>
</li>
<li>Elotuzumab + bortezomib + dexamethasone<br>
</li>
<li>Ixazomib + lenalidomide + dexamethasone<br>
</li>
<li>Ixazomib + cyclophosphamide + dexamethasone</li>
</ul>
</section>
<section id="晚期复发-late-relapses-3-次既往治疗" class="level4">
<h4 class="anchored" data-anchor-id="晚期复发-late-relapses-3-次既往治疗">晚期复发 (Late Relapses, &gt;3 次既往治疗)</h4>
<ul>
<li><strong>在 ≥4 次既往治疗后（包括抗 CD38 单抗 (anti-CD38 mAb)、蛋白酶体抑制剂 (PI)、免疫调节剂 (IMiD)）：</strong>
<ul>
<li>Ciltacabtagene autoleucel<br>
</li>
<li>Idecabtagene vicleucel<br>
</li>
<li>Elranatamab-bcmm<br>
</li>
<li>Talquetamab-tgvs<br>
</li>
<li>Teclistamab-cqyv</li>
</ul></li>
<li><strong>其他推荐方案：</strong>
<ul>
<li>Bendamustine<br>
</li>
<li>Bendamustine + bortezomib + dexamethasone<br>
</li>
<li>Bendamustine + carfilzomib + dexamethasone<br>
</li>
<li>Bendamustine + lenalidomide + dexamethasone<br>
</li>
<li>大剂量或分次 cyclophosphamide (high-dose or fractionated cyclophosphamide)</li>
</ul></li>
</ul>
</section>
<section id="其他说明" class="level4">
<h4 class="anchored" data-anchor-id="其他说明">其他说明</h4>
<ul>
<li><strong>Bortezomib</strong> 推荐使用皮下注射 (subcutaneous)，而不是静脉注射 (intravenous)<br>
</li>
<li><strong>CAR T 细胞治疗 (CAR T-cell therapy)</strong>：适用于 lenalidomide 耐药患者，若：
<ul>
<li>1 次既往治疗后，包含 IMiD + PI（ciltacabtagene autoleucel）<br>
</li>
<li>2 次既往治疗后，包含 IMiD + 抗 CD38 单抗 + PI（idecabtagene vicleucel）</li>
</ul></li>
<li><strong>其他复发时可选方案：</strong>
<ul>
<li>Daratumumab + pomalidomide + dexamethasone<br>
</li>
<li>Isatuximab-irfc + pomalidomide + dexamethasone<br>
</li>
<li>Pomalidomide + cyclophosphamide + dexamethasone<br>
</li>
<li>Selinexor + dexamethasone（用于晚期复发，且对 ≥2 种 PI、≥2 种 IMiD 和抗 CD38 单抗均耐药）</li>
</ul></li>
</ul>
</section>
</section>
<section id="维持治疗-maintenance-therapy" class="level3">
<h3 class="anchored" data-anchor-id="维持治疗-maintenance-therapy">维持治疗 (Maintenance Therapy)</h3>
<ul>
<li><p>定义：在 multiple myeloma 患者经过初始治疗后，对于已获得缓解或疾病未进展的患者给予的进一步治疗，目标是延长生存 (prolong survival)。</p></li>
<li><p>首选药物 (Preferred Agents)</p>
<ul>
<li>Lenalidomide</li>
</ul></li>
<li><p>移植患者 (Transplant) 可选方案：</p>
<ul>
<li>Bortezomib<br>
</li>
<li>Bortezomib + Lenalidomide<br>
</li>
<li>Carfilzomib + Lenalidomide<br>
</li>
<li>Daratumumab ± Lenalidomide<br>
</li>
<li>Ixazomib</li>
</ul></li>
<li><p>非移植患者 (Non-Transplant) 可选方案：</p>
<ul>
<li>Bortezomib<br>
</li>
<li>Bortezomib + Lenalidomide 或 Ixazomib</li>
</ul></li>
</ul>
<section id="临床试验证据-clinical-trials" class="level4">
<h4 class="anchored" data-anchor-id="临床试验证据-clinical-trials">临床试验证据 (Clinical Trials)</h4>
<ul>
<li><strong>Lenalidomide</strong>
<ul>
<li>国际 III 期随机试验 (614例)：自体移植后使用 Lenalidomide 维持治疗的患者，中位无进展生存 (PFS) 为41个月，对照组 (安慰剂) 为23个月。<br>
</li>
<li>III 期随机试验 (459例)：在 MPL (Melphalan, Prednisone, Lenalidomide) 初始治疗后，Lenalidomide 维持治疗使 PFS 提高 66%。</li>
</ul></li>
</ul>
<blockquote class="blockquote">
<p>Lenalidomide 维持治疗患者发生继发性肿瘤 (secondary cancers) 的风险增加，尤其是移植后。</p>
</blockquote>
<ul>
<li><strong>Bortezomib</strong>
<ul>
<li>III 期随机试验：单药 Bortezomib 维持治疗耐受性良好；在 Bortezomib 联合方案 (如 Bortezomib + Dexamethasone，Bortezomib + Thalidomide + Dexamethasone 等) 后维持治疗，反应率进一步提高。<br>
</li>
<li>III 期随机试验：自体移植后使用 Bortezomib 维持，近完全缓解 (CR) 和完全缓解 (CR) 的比例更高，耐受性良好，且未增加周围神经病变 (peripheral neuropathy)。</li>
</ul></li>
</ul>
</section>
</section>
</section>
<section id="药物" class="level2">
<h2 class="anchored" data-anchor-id="药物">药物</h2>
<p>用于治疗多发性骨髓瘤的一些常用药物包括：</p>
<ul>
<li><p>免疫调节剂：如雷莫尼敏 (<a href="../../../docs/pharmaceutical/compound/Revlimid.html">Revlimid</a> (Lenalidomide)) 和硫利达嗪 (<a href="../../../docs/pharmaceutical/compound/Thalidomide.html">Thalidomide</a>)</p>
<blockquote class="blockquote">
<p>免疫调节剂（IMiDs）通过增强 T 细胞和自然杀伤细胞的活性来攻击肿瘤，同时抑制骨髓瘤细胞的生长因子信号。它们还能抑制<a href="../../../docs/pharmaceutical/other/TME.html">肿瘤微环境</a>中新生血管的形成。常见副作用包括血细胞减少、血栓风险和疲劳。</p>
</blockquote></li>
<li><p>CELMoD（Cereblon E3 Ligase Modulator，新一代免疫调节剂）：如<a href="../../../docs/pharmaceutical/compound/Iberdomide.html">Iberdomide</a>, <a href="../../../docs/pharmaceutical/compound/Mezigdomide.html">Mezigdomide</a></p>
<blockquote class="blockquote">
<p>CELMoDs 通过更强效地结合并调节 cereblon 蛋白，从而促进 Ikaros 和 Aiolos 的降解，抑制骨髓瘤细胞增殖，并增强 T 细胞和NK细胞活性。它们在 IMiDs 失效后的患者中仍然有效，是下一代骨髓瘤免疫调节治疗的核心。常见副作用包括中性粒细胞减少和感染风险。</p>
</blockquote></li>
<li><p>Proteasome Inhibitor (蛋白酶体抑制剂)：如波特莫德 (<a href="../../../docs/pharmaceutical/compound/Bortezomib.html">Bortezomib</a>) 和卡菲佐米 (<a href="../../../docs/pharmaceutical/compound/Carfilzomib.html">Carfilzomib</a>)</p>
<blockquote class="blockquote">
<p>蛋白酶体抑制剂通过阻断细胞内蛋白降解通道（26S 蛋白酶体），导致异常蛋白堆积，从而触发骨髓瘤细胞凋亡。它们尤其能克服骨髓瘤细胞对常规治疗的耐药性。典型副作用包括外周神经病变和胃肠道症状。</p>
</blockquote></li>
<li><p>皮质类固醇：如地塞米松 (Dexamethasone)</p>
<blockquote class="blockquote">
<p>类固醇不仅具有抗炎和免疫抑制作用，还能直接诱导骨髓瘤细胞凋亡。它们通常作为联合疗法的一部分来增强疗效。长期使用可能带来高血糖、感染风险和骨质疏松等问题。</p>
</blockquote></li>
<li><p>CAR-T细胞疗法：如 <a href="../../../docs/pharmaceutical/compound/Abecma.html">Abecma</a> 和 <a href="../../../docs/pharmaceutical/compound/Carvykti.html">Carvykti</a></p>
<blockquote class="blockquote">
<p>CAR-T 疗法是一种个体化免疫疗法，将患者自身的 T 细胞在体外进行基因修饰，使其表达嵌合抗原受体（CAR），从而识别并杀伤骨髓瘤细胞。目前多针对 <strong>BCMA</strong>（B细胞成熟抗原）。该疗法可以带来深度缓解，但副作用包括细胞因子释放综合征（CRS）和神经毒性。</p>
</blockquote></li>
<li><p>单克隆抗体：这些药物通过靶向肿瘤细胞上的特定分子来发挥作用。例如，达雷妥珠单抗（<a href="../../../docs/pharmaceutical/compound/Darzalex.html">Darzalex</a> (Daratumumab)）靶向CD38，一个在多发性骨髓瘤细胞表面常见的分子。</p>
<blockquote class="blockquote">
<p>单抗通过结合肿瘤相关抗原，引导免疫系统（如补体依赖细胞毒作用和抗体依赖细胞毒作用）清除骨髓瘤细胞。它们常与 IMiDs 或 PIs 联用。主要不良事件包括输注反应和感染风险。</p>
</blockquote></li>
</ul>
<section id="蛋白酶体抑制剂proteasome-inhibitors" class="level3">
<h3 class="anchored" data-anchor-id="蛋白酶体抑制剂proteasome-inhibitors">蛋白酶体抑制剂（Proteasome Inhibitors）</h3>
<ul>
<li><p>multiple myeloma 细胞主要位于骨髓（Bone marrow），通过与骨髓基质细胞结合，诱导细胞因子（IL-6, IGF-1, GDF15）的分泌，促进细胞增殖和存活，同时抵抗化疗药物作用。</p></li>
<li><p>蛋白酶体（26S proteasome）是细胞内负责降解泛素化蛋白（Ubiquitinated proteins）的关键结构。在 myeloma cells 中，蛋白酶体可降解抑癌蛋白（如 p53），促进肿瘤细胞生存。<br>
</p></li>
<li><p>蛋白酶体抑制剂通过阻断这一通路，使异常蛋白累积，导致肿瘤细胞凋亡。</p></li>
</ul>
<p><strong>主要药物：</strong></p>
<ul>
<li><strong>Bortezomib</strong>：首个获批用于 multiple myeloma 的蛋白酶体抑制剂，可静脉或皮下注射。疗效显著，但常见不良反应包括耐药及剂量限制性毒性——外周神经病变（Peripheral neuropathy）。<br>
</li>
<li><strong>Carfilzomib</strong>：同样抑制 26S proteasome，但结合位点不同。用于复发/难治性 multiple myeloma（RRMM），静脉给药。不良反应发生率低于 bortezomib，尤其是外周神经病变（约 11%）。<br>
</li>
<li><strong>Ixazomib</strong>：首个口服蛋白酶体抑制剂，常与来那度胺（Lenalidomide）和地塞米松（Dexamethasone）联合使用。适用于经治患者，外周神经病变发生率约 31%。</li>
</ul>
<p><strong>外周神经病变风险（Peripheral neuropathy）：</strong></p>
<ul>
<li>Bortezomib 静脉给药：约 39% 患者出现。<br>
</li>
<li>Bortezomib 皮下注射：约 20% 患者出现。<br>
</li>
<li>Carfilzomib：约 11% 患者出现。<br>
</li>
<li>Ixazomib：约 31% 患者出现。</li>
</ul>
</section>
<section id="免疫调节剂immunomodulatory-drugs-imids" class="level3">
<h3 class="anchored" data-anchor-id="免疫调节剂immunomodulatory-drugs-imids">免疫调节剂（Immunomodulatory Drugs, IMiDs）</h3>
<ul>
<li>IMiDs 是一类通过调节患者免疫系统而发挥抗肿瘤作用的药物，主要代表包括 Thalidomide、Lenalidomide 和 Pomalidomide。</li>
</ul>
<p><strong>Thalidomide</strong></p>
<ul>
<li>机制：增强免疫反应，抑制肿瘤坏死因子 α（TNF-α）、白细胞介素（Interleukins）、干扰素（Interferons），并抑制 VEGF 和 bFGF，减少肿瘤血管生成。<br>
</li>
<li>常见不良反应：外周神经病变（Peripheral neuropathy）、疲劳、低钙血症、白细胞/中性粒细胞减少、便秘、水肿、皮疹、呼吸困难、肌无力。<br>
</li>
<li>特殊注意：可导致深静脉血栓（Deep vein thrombosis）及严重胎儿畸形或死亡。育龄期女性必须严格避孕，患者需签署知情同意并接受风险管理。</li>
</ul>
<p><strong>Lenalidomide</strong></p>
<ul>
<li>机制：Thalidomide 的衍生物，神经毒性更低，抗癌活性增强。<br>
</li>
<li>常见不良反应：中性粒细胞减少、红细胞减少、疲劳、便秘、腹泻、肌肉痉挛。</li>
</ul>
<p><strong>Pomalidomide</strong></p>
<ul>
<li>机制：同样是 Thalidomide 衍生物，通过结构改造显著增强对 T 细胞的刺激作用（&gt;1000 倍）。<br>
</li>
<li>常见不良反应：上呼吸道感染、疲劳、白细胞和红细胞减少、便秘、恶心、腹泻、呼吸困难、背痛。</li>
</ul>
<p><strong>风险管理</strong></p>
<ul>
<li>IMiDs 类药物均有导致深静脉血栓（DVT）和严重出生缺陷的风险。<br>
</li>
<li>治疗期间需合并抗凝预防，并严格执行避孕和患者监控计划。</li>
</ul>
</section>
<section id="corticosteroids糖皮质激素" class="level3">
<h3 class="anchored" data-anchor-id="corticosteroids糖皮质激素">Corticosteroids（糖皮质激素）</h3>
<p>Corticosteroids，尤其是 <strong>glucocorticosteroids</strong>，由肾上腺分泌，在 multiple myeloma 的治疗中常与 <strong>proteasome inhibitors (PI)</strong>、<strong>chemotherapy</strong> 或 <strong>IMiDs</strong> 联合使用，能够增强其他药物的抗肿瘤作用。</p>
<ul>
<li><strong>Glucocorticosteroid 的功能</strong>
<ul>
<li>调节糖类、蛋白质和脂肪的代谢<br>
</li>
<li>抑制炎症、过敏反应和部分正常免疫反应</li>
</ul></li>
<li><strong>Dexamethasone（地塞米松）</strong>
<ul>
<li>抑制白细胞向炎症部位迁移<br>
</li>
<li>减少肿瘤周围水肿<br>
</li>
<li>缓解疼痛</li>
</ul></li>
<li><strong>常见的不良反应（Adverse Reactions）</strong>
<ul>
<li>感染、伤口愈合延迟、皮疹<br>
</li>
<li>血压升高、水肿、胃肠穿孔、恶心、呕吐、胃灼热<br>
</li>
<li>体重增加、高血糖、骨质疏松、青光眼、白内障<br>
</li>
<li>情绪波动、抑郁、失眠、过敏反应</li>
</ul></li>
<li><strong>其他常用药物</strong>
<ul>
<li><strong>Prednisone（泼尼松）</strong><br>
</li>
<li><strong>Prednisolone（泼尼松龙）</strong><br>
</li>
<li><strong>Methylprednisolone（甲泼尼龙）</strong></li>
</ul></li>
</ul>
</section>
<section id="chemotherapeutics化疗药物" class="level3">
<h3 class="anchored" data-anchor-id="chemotherapeutics化疗药物">Chemotherapeutics（化疗药物）</h3>
<p>在 multiple myeloma 的治疗中，化疗药物主要通过抑制 DNA 复制和干扰肿瘤细胞增殖来发挥作用，常与 <strong>dexamethasone</strong>、<strong>proteasome inhibitors</strong> 或 <strong>IMiDs</strong> 联合使用。</p>
<ul>
<li><strong>Doxorubicin（阿霉素）</strong>
<ul>
<li>嵌入 DNA 双螺旋碱基对之间，抑制拓扑异构酶 II<br>
</li>
<li>生成氧自由基（oxygen free radicals）<br>
</li>
<li>属于 <strong>anthracycline antibiotic</strong>，需静脉给药<br>
</li>
<li><strong>毒性反应</strong>：
<ul>
<li>心肌损伤（Myocardial damage）<br>
</li>
<li>手足综合征（Hand-Foot syndrome）</li>
</ul></li>
</ul></li>
<li><strong>Etoposide（依托泊苷）与 Cisplatin（顺铂）</strong>
<ul>
<li>Etoposide 抑制拓扑异构酶 II，阻断 DNA 复制<br>
</li>
<li>常与多药联合使用（例如 DT-PACE, VTD-PACE, DCEP）<br>
</li>
<li><strong>常见不良反应</strong>：
<ul>
<li>Cisplatin：肾功能损伤、周围神经病变、恶心、呕吐、耳毒性、骨髓抑制<br>
</li>
<li>Etoposide：粒细胞减少（Low neutrophil count）</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="stem-cell-transplantation干细胞移植" class="level3">
<h3 class="anchored" data-anchor-id="stem-cell-transplantation干细胞移植">Stem Cell Transplantation（干细胞移植）</h3>
<p>Hematopoietic stem cells（造血干细胞）主要存在于骨髓中，也可在外周血和脐带血中找到。干细胞移植的目的是恢复因治疗而受损的造血功能。</p>
<ul>
<li><strong>主要类型</strong>
<ul>
<li><strong>Autologous transplant（自体移植）</strong>：患者接受自己的干细胞<br>
</li>
<li><strong>Syngeneic transplant（同基因移植）</strong>：来自同卵双胞胎的干细胞<br>
</li>
<li><strong>Allogeneic transplant（异体移植）</strong>：来自 HLA 匹配的供体（可能是亲属或非亲属）</li>
</ul></li>
<li><strong>移植流程</strong>
<ul>
<li><strong>HLA 匹配（HLA antigens）</strong>：匹配度越高，移植物被接受的几率越大<br>
</li>
<li><strong>Apheresis（单采术）</strong>：通过静脉或中心静脉导管采集干细胞，经分离后保存<br>
</li>
<li><strong>冷冻保存（Cryopreservation）</strong>：干细胞在移植前冷冻储存，移植时静脉输注回患者体内</li>
</ul></li>
<li><strong>关键步骤</strong>
<ul>
<li><strong>Purging（清除）</strong>：自体移植中需清除癌细胞，降低复发风险（但也可能损失部分健康干细胞）<br>
</li>
<li><strong>Engraftment（植入）</strong>：移植干细胞迁移到骨髓，开始生成新的血细胞
<ul>
<li>自体移植通常数月内恢复<br>
</li>
<li>异体移植则可能需要长达两年</li>
</ul></li>
</ul></li>
<li><strong>并发症处理</strong>
<ul>
<li>移植过程中常用抗生素和输血支持，以减少感染和并发症风险</li>
</ul></li>
</ul>
</section>
<section id="monoclonal-antibodies单克隆抗体" class="level3">
<h3 class="anchored" data-anchor-id="monoclonal-antibodies单克隆抗体">Monoclonal Antibodies（单克隆抗体）</h3>
<p>单克隆抗体（mAbs）自 1990s 以来已广泛用于 B-cell lymphoma 等肿瘤治疗，在 multiple myeloma（MM）中也成为重要的靶向治疗手段。</p>
<ul>
<li><strong>已获批的 monoclonal antibodies（RRMM）</strong>
<ul>
<li><strong>Elotuzumab</strong>：靶向 SLAMF7，增强 NK 细胞介导的杀伤
<ul>
<li>常与 lenalidomide + dexamethasone 或 pomalidomide + dexamethasone 联合使用<br>
</li>
<li><strong>Adverse reactions</strong>: fatigue, diarrhea, fever, constipation, cough, hyperglycemia<br>
</li>
</ul></li>
<li><strong>Daratumumab</strong>：靶向 CD38，诱导肿瘤细胞凋亡
<ul>
<li>可单药或与 bortezomib、lenalidomide、thalidomide、carfilzomib、pomalidomide 等联合<br>
</li>
<li><strong>Adverse reactions</strong>: infusion reactions, cytopenias, diarrhea, nausea/vomiting, fatigue, peripheral neuropathy, upper respiratory infections<br>
</li>
</ul></li>
<li><strong>Isatuximab</strong>：同样靶向 CD38
<ul>
<li>常与 pomalidomide + dexamethasone 联合（NCCN 推荐为 RRMM 首选方案之一）<br>
</li>
<li><strong>Adverse reactions</strong>: neutropenia, infusion-related reactions, pneumonia, bronchitis, hypertension, cough, fatigue</li>
</ul></li>
</ul></li>
<li><strong>已获批的 bispecific monoclonal antibodies（双特异抗体）</strong>
<ul>
<li><strong>Teclistamab</strong>（BiTE，靶向 BCMA × CD3）
<ul>
<li>诱导 T 细胞杀伤 myeloma cells<br>
</li>
<li><strong>Adverse reactions</strong>: cytokine release syndrome (CRS), injection site reactions, fatigue, pneumonia, diarrhea<br>
</li>
</ul></li>
<li><strong>Elranatamab</strong>（BiTE，靶向 BCMA × CD3）
<ul>
<li>作用机制类似 Teclistamab<br>
</li>
<li><strong>Adverse reactions</strong>: CRS, musculoskeletal pain, fatigue, rash, cough, diarrhea<br>
</li>
</ul></li>
<li><strong>Talquetamab</strong>（BiTE，靶向 GPRC5D × CD3）
<ul>
<li>特异性靶向 GPRC5D，诱导 T 细胞介导的细胞死亡<br>
</li>
<li><strong>Adverse reactions</strong>: CRS, altered taste, dry mouth, difficulty swallowing, skin/nail disorders, weight loss, fatigue</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="car-t-cell-therapycar-t-细胞疗法" class="level3">
<h3 class="anchored" data-anchor-id="car-t-cell-therapycar-t-细胞疗法">CAR T-Cell Therapy（CAR-T 细胞疗法）</h3>
<p>CAR T-cell therapy 是近年来 multiple myeloma（MM）治疗中的重要突破，主要靶向 <strong>BCMA（B-cell maturation antigen）</strong>。</p>
<ul>
<li><strong>已批准疗法</strong>
<ul>
<li><strong>Idecabtagene vicleucel (ide-cel)</strong>：适用于 RRMM，需 ≥2 线既往治疗后<br>
</li>
<li><strong>Ciltacabtagene autoleucel (cilta-cel)</strong>：适用于 RRMM，需 ≥1 线既往治疗后</li>
</ul></li>
<li><strong>特点</strong>
<ul>
<li>仅用于 <strong>autologous therapy（自体疗法）</strong><br>
</li>
<li>输注前需进行 <strong>lymphodepleting chemotherapy</strong>（如 cyclophosphamide + fludarabine）<br>
</li>
<li>属于一次性个体化细胞疗法</li>
</ul></li>
<li><strong>安全性与风险</strong>
<ul>
<li>盒装警告（Boxed warnings）：
<ul>
<li>Cytokine release syndrome (CRS)<br>
</li>
<li>Neurologic toxicities<br>
</li>
<li>Hemophagocytic lymphohistiocytosis/macrophage activation syndrome (HLH/MAS)<br>
</li>
<li>Prolonged cytopenias<br>
</li>
<li>Secondary hematologic malignancies<br>
</li>
</ul></li>
<li>仅在 <strong>REMS（Risk Evaluation and Mitigation Strategy）项目</strong>下可用</li>
</ul></li>
</ul>
</section>
<section id="other-recently-approved-therapies近期获批疗法" class="level3">
<h3 class="anchored" data-anchor-id="other-recently-approved-therapies近期获批疗法">Other Recently Approved Therapies（近期获批疗法）</h3>
<p>除了传统化疗、IMiDs、PIs、mAbs 和 CAR-T 等，部分新药也在 multiple myeloma 的治疗中显示出疗效。</p>
<ul>
<li><strong>Selinexor</strong>
<ul>
<li>FDA 于 2019 年批准，与 bortezomib 和 dexamethasone 联合使用<br>
</li>
<li>口服核输出抑制剂（nuclear export inhibitor），可可逆性阻断 exportin 1 (XPO1)，抑制肿瘤抑制蛋白（TSPs）、生长调控因子及致癌蛋白 mRNAs 的核输出<br>
</li>
<li><strong>Adverse reactions</strong>:
<ul>
<li>细胞减少（白细胞、血小板、淋巴细胞、红细胞、中性粒细胞）<br>
</li>
<li>发热、疲劳、恶心、呕吐、腹泻、食欲下降、体重减轻<br>
</li>
<li>外周神经病变、低钠血症、便秘、呼吸困难、上呼吸道感染</li>
</ul></li>
</ul></li>
<li><strong>Venetoclax</strong>
<ul>
<li>小分子抑制剂，作用于 <strong>BCL-2</strong>，阻断其与促凋亡蛋白结合，从而激活细胞内源性凋亡通路<br>
</li>
<li>FDA 已批准用于 <strong>CLL（慢性淋巴细胞白血病）</strong>、<strong>SLL（小淋巴细胞淋巴瘤）</strong> 和 <strong>AML（急性髓性白血病）</strong>，并在 multiple myeloma 中研究应用<br>
</li>
<li><strong>Adverse reactions</strong>:
<ul>
<li>恶心、呕吐、腹泻<br>
</li>
<li>血小板减少、中性粒细胞减少、红细胞减少、白细胞减少、淋巴细胞减少</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="支持治疗supportive-care" class="level3">
<h3 class="anchored" data-anchor-id="支持治疗supportive-care">支持治疗（Supportive care）</h3>
<ul>
<li><p>概述：multiple myeloma 常并发骨病（bone disease）、贫血（anemia）、血栓（blood clots）、高钙血症（hypercalcemia）、肾功能不全（kidney dysfunction）、感染（infection）；需在抗肿瘤治疗同时并行支持治疗。</p></li>
<li><p>骨病（Bone disease）</p>
<ul>
<li>发生率约 80–85%；表现为骨量减少/溶骨性病灶（osteopenia/osteolytic lesions）。</li>
<li>双磷酸盐（bisphosphonates：pamidronate、zoledronic acid）：
<ul>
<li>预防进一步骨破坏；减轻骨痛、减少镇痛药使用；</li>
<li>纠正/预防高钙血症；降低病理性骨折与放疗需求；改善生活质量（QoL）。</li>
</ul></li>
<li>地舒单抗（denosumab）：
<ul>
<li>肾功能不全患者的优选替代方案；每 4 周皮下注射（SC）。</li>
<li>常见不良反应（AEs）：腹泻（diarrhea）、恶心（nausea）、红细胞减少（low RBC）、背痛（back pain）。</li>
</ul></li>
<li>介入/外科（interventional/surgery）：
<ul>
<li>椎体成形术（vertebroplasty）：椎体内注射骨水泥（bone cement）以增强稳定性；</li>
<li>椎体后凸成形术（kyphoplasty）：球囊扩张后注射骨水泥。</li>
</ul></li>
</ul></li>
<li><p>其他并发症处理（Management of other complications）</p>
<ul>
<li>贫血（anemia）：输血（blood transfusion）、促红素（erythropoietin）。</li>
<li>高钙血症（hypercalcemia）：等渗盐水强化补液（aggressive hydration with saline）、双磷酸盐、激素（steroids）、降钙素（calcitonin）。</li>
<li>肾功能不全（renal insufficiency）：补液（hydration）、血浆置换（plasmapheresis，用于高黏滞）、血液/腹膜透析（hemodialysis/peritoneal dialysis）、避免 NSAIDs。</li>
<li>感染（infection）：抗菌药物（antibiotics）；预防性疫苗（pneumococcal、influenza、shingles、COVID-19）。</li>
<li>血栓（blood clots）：阿司匹林（aspirin）或抗凝药（anticoagulants）。</li>
</ul></li>
</ul>
</section>
</section>
<section id="responses-疗效反应标准" class="level2">
<h2 class="anchored" data-anchor-id="responses-疗效反应标准">Responses 疗效反应标准</h2>
<ul>
<li><strong>Stringent complete response (sCR)</strong>
<ul>
<li>符合完全缓解 (CR) 标准</li>
<li>free light chain (FLC) 比值正常</li>
<li>骨髓活检免疫组化检测无克隆性浆细胞</li>
</ul></li>
<li><strong>Complete response (CR)</strong>
<ul>
<li>血清和尿液免疫固定检测 (immunofixation) 阴性</li>
<li>软组织浆细胞瘤消失</li>
<li>骨髓浆细胞 &lt; 5%</li>
<li>若仅依靠血清 FLC 检测疾病：FLC 比值在 0.26–1.65 正常范围内</li>
</ul></li>
<li><strong>Very good partial response (VGPR)</strong>
<ul>
<li>血清/尿液 M 蛋白可被免疫固定检测到，但电泳检测不到</li>
<li>血清 M 蛋白下降 ≥90%，且尿液 M 蛋白 &lt;100 mg/24h</li>
<li>若仅依靠血清 FLC 检测疾病：FLC 差值下降 &gt;90%</li>
</ul></li>
<li><strong>Partial response (PR)</strong>
<ul>
<li>血清 M 蛋白下降 ≥50%，尿液 M 蛋白下降 ≥90% 或 &lt;200 mg/24h</li>
<li>若血清/尿液 M 蛋白不可测：FLC 差值下降 ≥50%</li>
<li>若 serum free light assay 也不可测：骨髓浆细胞减少 ≥50%，且基线浆细胞 ≥30%</li>
<li>若基线存在软组织浆细胞瘤：体积减少 ≥50%</li>
</ul></li>
<li><strong>Minimal response (MR)</strong>
<ul>
<li>血清 M 蛋白下降 25–49%，尿液 M 蛋白下降 50–89%</li>
<li>若基线存在软组织浆细胞瘤：体积减少 25–49%</li>
</ul></li>
<li><strong>Stable disease (SD)</strong>
<ul>
<li>不符合 CR、VGPR、PR、MR 或 PD 标准</li>
<li>不推荐作为反应评价指标，更适合用于 PFS 或 TTP</li>
</ul></li>
<li><strong>MRD-negative (微小残留病灶阴性)</strong>
<ul>
<li><strong>Sustained MRD-negative</strong>: 骨髓 MRD 阴性 (NGF 或 NGS)，间隔 ≥1 年复查仍阴性，可随访至 5 年</li>
<li><strong>Flow MRD-negative</strong>: NGF 检测骨髓无克隆性浆细胞，敏感度 ≥1/10^5</li>
<li><strong>Sequencing MRD-negative</strong>: NGS 检测无克隆性浆细胞（少于 2 个相同序列），敏感度 ≥1/10^5</li>
<li><strong>Imaging plus MRD-negative</strong>:
<ul>
<li>FDG PET/CT 显示无异常摄取</li>
<li>或 SUV 低于纵隔血池/正常组织水平</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="disease-progression" class="level2">
<h2 class="anchored" data-anchor-id="disease-progression">Disease Progression</h2>
<ul>
<li><strong>Progressive Disease</strong>
<ul>
<li>基于以下任一标准：
<ul>
<li>血清 M-component 增加 ≥25%（绝对增加 ≥0.5 g/dL）；如果基线 M ≥5 g/dL，增加 ≥1 g/dL 即可定义复发</li>
<li>尿液 M-component 增加 ≥25%（绝对增加 ≥200 mg/24h）</li>
<li>若血清和尿液 M-protein 不可测：involved/uninvolved FLC 差值绝对增加 &gt;10 mg/dL</li>
<li>若血清/尿液 M-protein 和 FLC 水平均不可测：骨髓浆细胞比例 ≥10%</li>
<li>出现新的骨损害或软组织浆细胞瘤，或已有病灶体积明显增加</li>
<li>外周血浆细胞增加 ≥50%（且 ≥200 cells/µL），若这是唯一可测疾病</li>
</ul></li>
</ul></li>
<li><strong>Clinical Relapse</strong>
<ul>
<li>满足以下任一条件：
<ul>
<li>出现直接的疾病进展/器官功能损害迹象（高钙血症、肾衰、贫血、溶骨性骨损害）</li>
<li>新发软组织浆细胞瘤或骨病灶</li>
<li>已有病灶体积增加 ≥50% 且至少直径 ≥1 cm</li>
<li>高钙血症（&gt;11 mg/dL）</li>
<li>血红蛋白下降 ≥2 g/dL，且非治疗或其他非 myeloma 原因</li>
<li>血清肌酐升高 ≥2 mg/dL，且归因于 myeloma</li>
<li>与血清副蛋白相关的高黏滞综合征</li>
</ul></li>
</ul></li>
<li><strong>Relapse from Complete Response (CR)</strong>
<ul>
<li>满足以下任一条件：
<ul>
<li>血清或尿液 M-protein 复现（免疫固定或电泳检测）</li>
<li>骨髓浆细胞比例 ≥5%</li>
<li>出现任何其他进展迹象（新发浆细胞瘤、溶骨性骨损害、高钙血症）</li>
</ul></li>
</ul></li>
<li><strong>Relapse from MRD Negative</strong>
<ul>
<li>满足以下任一条件：
<ul>
<li>失去 MRD 阴性状态（NGF/NGS 证据，或影像学复发）</li>
<li>血清或尿液 M-protein 复现</li>
<li>骨髓克隆浆细胞比例 ≥5%</li>
<li>出现其他疾病进展迹象（如新发浆细胞瘤、溶骨性骨损害、高钙血症）</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="treatment-strategy-for-different-patients" class="level2">
<h2 class="anchored" data-anchor-id="treatment-strategy-for-different-patients">Treatment Strategy for different patients</h2>
<ul>
<li>确定不同患者的治疗方法：原发性浆细胞瘤 (primary plasmacytoma)、无症状 myeloma (asymptomatic myeloma)、以及活动性 myeloma (active myeloma)<br>
</li>
<li>说明维持治疗 (maintenance therapy) 和挽救治疗 (salvage therapy) 的目的，并明确常用药物</li>
</ul>
<section id="solitary-plasmacytoma-孤立性浆细胞瘤" class="level3">
<h3 class="anchored" data-anchor-id="solitary-plasmacytoma-孤立性浆细胞瘤">Solitary Plasmacytoma (孤立性浆细胞瘤)</h3>
<ul>
<li>随访监测 (Follow-Up Monitoring)
<ul>
<li>血液和尿液检测、影像学检查<br>
</li>
<li>疾病敏感性通过 M 蛋白 (M-protein) 的定期监测确认<br>
</li>
<li>至少每年做一次影像学检查</li>
</ul></li>
</ul>
</section>
<section id="asymptomatic-myeloma" class="level3">
<h3 class="anchored" data-anchor-id="asymptomatic-myeloma">Asymptomatic Myeloma</h3>
<ul>
<li>特点：无症状、无器官损伤<br>
</li>
<li>高危标准 (High Risk)：若满足以下≥2项
<ul>
<li>骨髓浆细胞 &gt;20%<br>
</li>
<li>血清游离轻链 (serum free light chain) 比值 &gt;20<br>
</li>
<li>M 蛋白 &gt;2 g/dL<br>
</li>
</ul></li>
<li>监测建议 (Monitoring)
<ul>
<li>CBC + 血小板计数<br>
</li>
<li>血清肌酐、白蛋白、校正钙<br>
</li>
<li>定量免疫球蛋白、SPEP、SIFE<br>
</li>
<li>FLC 检测（必要时）<br>
</li>
<li>24小时尿蛋白，UPEP、UIFE<br>
</li>
<li>骨髓穿刺 + FISH/SNP array/NGS 或 多参数流式<br>
</li>
<li>影像学（CT、MRI、FDG PET/CT），每年或按需<br>
</li>
</ul></li>
<li>NCCN 建议
<ul>
<li>高危患者：强烈推荐参加临床试验<br>
</li>
<li>无法试验：每 3 个月随访<br>
</li>
<li>少部分高危患者可用 Lenalidomide<br>
</li>
<li>低危患者：临床试验或每 3-6 个月随访</li>
</ul></li>
</ul>
</section>
<section id="active-myelomaprimary-therapy" class="level3">
<h3 class="anchored" data-anchor-id="active-myelomaprimary-therapy">Active Myeloma（Primary Therapy）</h3>
<ul>
<li>有症状/活动性患者接受初始治疗 (primary therapy)<br>
</li>
<li>后续可进入大剂量化疗 (high-dose chemotherapy) + 干细胞移植 (SCT)<br>
</li>
<li>进入 SCT 前需评估肝、肾、肺、心功能</li>
</ul>
</section>
<section id="active-myelomapreferred-agents" class="level3">
<h3 class="anchored" data-anchor-id="active-myelomapreferred-agents">Active Myeloma（Preferred Agents）</h3>
<ul>
<li>移植适用患者 (Transplant candidates)
<ul>
<li>Bortezomib/Lenalidomide/Dexamethasone<br>
</li>
<li>Carfilzomib/Lenalidomide/Dexamethasone<br>
</li>
<li>Ixazomib/Lenalidomide/Dexamethasone（部分患者）<br>
</li>
</ul></li>
<li>非移植患者 (Non-transplant candidates)
<ul>
<li>Bortezomib/Lenalidomide/Dexamethasone<br>
</li>
<li>Daratumumab/Lenalidomide/Dexamethasone<br>
</li>
</ul></li>
<li>治疗方式
<ul>
<li>周期性给药，持续多个周期<br>
</li>
<li>同时进行支持治疗 (supportive care)<br>
</li>
<li>监测疗效和不良反应</li>
</ul></li>
</ul>
</section>
<section id="active-myelomasct" class="level3">
<h3 class="anchored" data-anchor-id="active-myelomasct">Active Myeloma（SCT）</h3>
<ul>
<li>自体移植 (Autologous SCT)
<ul>
<li>一线或难治/复发时均可带来生存获益<br>
</li>
</ul></li>
<li>双次移植 (Tandem SCT)
<ul>
<li>适用于首次移植未达 CR/VGPR 患者<br>
</li>
<li>可带来 2–3 年以上缓解<br>
</li>
</ul></li>
<li>异基因移植 (Allogeneic SCT)
<ul>
<li>可能避免肿瘤细胞再输注<br>
</li>
<li>移植物抗肿瘤效应 (graft-versus-tumor) 可能带来额外获益</li>
</ul></li>
</ul>
</section>
</section>
<section id="与myeloma的关系" class="level2">
<h2 class="anchored" data-anchor-id="与myeloma的关系">与Myeloma的关系</h2>
<p>MM和Myeloma这两个术语经常被交替使用，但它们之间存在细微的差别：</p>
<ul>
<li>多发性骨髓瘤 (Multiple Myeloma, MM)：这是一种血液癌症，主要影响造血骨髓内的浆细胞。“多发性”意味着疾病影响骨髓的多个部位。MM通常导致一系列并发症，如骨损伤、高钙血症、肾功能受损、贫血等。</li>
<li>骨髓瘤 (Myeloma)：这个术语在临床上通常也指多发性骨髓瘤。然而，从字面上讲，“骨髓瘤”这个词可以被解释为任何形式的骨髓肿瘤，包括但不限于多发性骨髓瘤。在某些情况下，它可能被用来描述更广泛的相关病变，如孤立性骨髓瘤（Solitary Myeloma，也称为骨髓瘤性斑块）或浆细胞病（Plasmacytoma），后者通常指单个而不是多个浆细胞肿瘤。</li>
</ul>
</section>
<section id="与aml的区别" class="level2">
<h2 class="anchored" data-anchor-id="与aml的区别">与AML的区别</h2>
<p>多发性骨髓瘤（Multiple Myeloma, MM）和急性髓系白血病（Acute Myeloid Leukemia, AML）是两种不同的血液病，它们在细胞起源、发病机制、临床表现和治疗方法上有显著差异。</p>
<ul>
<li>多发性骨髓瘤（MM）
<ul>
<li>细胞起源：影响浆细胞，这是一种成熟的白细胞，主要功能是产生抗体。</li>
<li>特点：浆细胞在骨髓中异常增生，可能导致骨破坏、高钙血症、贫血、肾脏损伤等。</li>
<li>症状：骨痛、贫血、肾功能受损、高钙血症、感染易发。</li>
<li>治疗：主要包括化疗、靶向治疗、生物治疗、放疗和干细胞移植。</li>
</ul></li>
<li>急性髓系白血病（AML）
<ul>
<li>细胞起源：影响骨髓中的幼稚髓系细胞，这些细胞本应发育成为各种成熟的白血细胞。</li>
<li>特点：这些幼稚细胞在骨髓中快速增生并积聚，影响正常血细胞的产生。</li>
<li>症状：贫血、出血倾向、感染易发、疲劳、发热。</li>
<li>治疗：主要是强烈的化疗，有时候需要干细胞移植。</li>
</ul></li>
</ul>
<p>主要区别</p>
<ul>
<li>发病细胞类型：MM涉及浆细胞，而AML涉及幼稚的骨髓细胞。</li>
<li>症状和表现：两者的症状有重叠，但MM更注重骨痛和肾损伤，而AML的特征是出血倾向和感染。</li>
<li>治疗方法：虽然两者都可能使用化疗和干细胞移植，但AML的治疗通常更加激进。</li>
<li>发病机制和进展：AML通常进展更快，需要紧急治疗，而MM的进展相对较慢。</li>
</ul>


</section>

</main> <!-- /main -->
<script type="text/javascript">

// replace cmd keyboard shortcut w/ control on non-Mac platforms
const kPlatformMac = typeof navigator !== 'undefined' ? /Mac/.test(navigator.platform) : false;
if (!kPlatformMac) {
   var kbds = document.querySelectorAll("kbd")
   kbds.forEach(function(kbd) {
      kbd.innerHTML = kbd.innerHTML.replace(/⌘/g, '⌃');
   });
}

// tweak headings in pymd
document.querySelectorAll(".pymd span.co").forEach(el => {
   if (!el.innerText.startsWith("#|")) {
      el.style.fontWeight = 1000;
   }
});

</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../../docs/pharmaceutical/disease/MDS.html" class="pagination-link" aria-label="Myelodysplastic Syndromes (MDS)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Myelodysplastic Syndromes (MDS)</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../../docs/pharmaceutical/disease/Melanoma.html" class="pagination-link" aria-label="Melanoma">
        <span class="nav-page-text">Melanoma</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/eugenesun14">
      <i class="bi bi-twitter" role="img" aria-label="Quarto Twitter">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/EugeneHao">
      <i class="bi bi-github" role="img" aria-label="Quarto GitHub">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/hao-sun-13207/">
      <i class="bi bi-linkedin" role="img" aria-label="Quarto Linkedin">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>