---
title: "Leukemia"
---

白血病（Leukemia）是一种影响血液和骨髓的癌症类型。它主要涉及体内造血系统，尤其是白血细胞。白血病的特点是骨髓中白血细胞的异常增生和成熟过程受损，导致大量不成熟或功能异常的白血细胞进入血液循环。

::: {.callout-note collapse="true" title="大量不成熟或功能异常的白血细胞进入血液循环的危害"}
-   免疫功能受损：正常成熟的白血细胞对抵抗感染至关重要。不成熟或功能异常的白血细胞无法有效执行免疫防御功能，导致个体对感染的抵抗力下降。
-   影响正常血细胞的产生：在某些血液疾病，如白血病中，异常白血细胞在骨髓中的积聚会抑制正常血细胞的生成。这可能导致贫血（红细胞减少）、出血倾向（血小板减少）和增加的感染风险（正常白细胞减少）。
-   血液粘稠度增加：异常细胞的积聚可能增加血液的粘稠度，影响血液流动，从而增加血栓和循环问题的风险。
-   骨髓功能障碍：长期的异常细胞增生可能导致骨髓功能障碍，影响其造血能力。
-   症状和并发症：症状可能包括疲劳、虚弱、体重减轻、发热、出血和感染。在一些情况下，异常白血细胞还可能导致器官受损和其他严重并发症。
:::

## 白血病的分类

白血病可以根据它的发展速度（急性或慢性）和影响的细胞类型（髓系或淋巴系）进行分类。

-   急性白血病：迅速进展，需要立即治疗。主要类型包括：
    -   急性淋巴细胞性白血病（Acute Lymphocytic Leukemia, ALL）：主要影响淋巴细胞。
    -   急性髓系白血病（[AML](#acute-myeloid-leukemia)）：主要影响骨髓细胞。
-   慢性白血病：进展较慢，可能在一段时间内无症状。主要类型包括：
    1.  慢性淋巴细胞性白血病（[CLL](#chronic-lymphocytic-leukemia)）：主要影响淋巴细胞。
    2.  慢性髓系白血病（CML）：主要影响骨髓细胞。

## 症状

白血病的症状可能包括：

-   疲劳和乏力
-   易发感染
-   发热或夜间盗汗
-   体重减轻
-   出血倾向（如鼻血或牙龈出血）
-   骨痛或关节痛
-   脾脏或肝脏肿大

## 治疗

白血病的治疗取决于其类型、病情的严重程度、患者的年龄和整体健康状况。治疗方法可能包括：

-   化疗：是最常见的治疗方式。
-   靶向治疗：针对癌细胞的特定特征。
-   放疗：在某些情况下使用。
-   干细胞移植：在某些类型的白血病中可能是一个选择。

## 白血细胞（White Blood Cells)

白血细胞（White Blood Cells, WBCs）是人体免疫系统的重要组成部分，主要功能是抵御感染和疾病。它们在血液中的数量相对较少，但在人体抵抗病原体（如细菌、病毒、寄生虫和真菌）方面发挥着关键作用。

### 白血细胞的类型

白血细胞分为几种不同类型，每种类型都有其独特的功能：

-   淋巴细胞 (Lymphocytes)：包括B细胞和T细胞，主要负责产生抗体，识别和消灭病原体和感染细胞，以及调节免疫反应。
    -   B细胞：产生抗体，与病原体结合，促进其清除。
    -   T细胞：分为辅助T细胞和细胞毒性T细胞，参与直接的细胞免疫反应。
-   髓系细胞 (Myeloid White Blood Cells)
    -   中性粒细胞 (Neutrophils)：是数量最多的白血细胞类型，主要参与消灭细菌和真菌。
    -   单核细胞 (Monocytes)：在组织中成熟为巨噬细胞或树突状细胞，吞噬和消化病原体和死细胞，以及呈递抗原。
    -   嗜酸性粒细胞 (Eosinophils) 和 嗜碱性粒细胞 (Basophils)：参与对抗寄生虫感染和过敏反应。

### 功能

-   抵御感染：白血细胞可以识别和消灭入侵的病原体。
-   免疫调节：调控身体的免疫反应。
-   炎症反应：在炎症反应中发挥重要作用，帮助修复受损组织。

### 白细胞发展过程

1.  干细胞阶段

-   造血干细胞（Hematopoietic Stem Cells, HSCs）：所有血细胞，包括白细胞、红细胞和血小板，都源自于骨髓中的多能造血干细胞。这些干细胞具有自我更新和分化成不同血细胞的能力。

2.  分化为两大系列

-   髓系（Myeloid Lineage）：造血干细胞分化为髓系前体细胞，最终形成中性粒细胞、嗜酸性粒细胞、嗜碱性粒细胞、单核细胞（进一步成熟为巨噬细胞和树突状细胞）等。
-   淋巴系（Lymphoid Lineage）：造血干细胞也可以分化为淋巴系前体细胞，最终形成淋巴细胞，包括B细胞、T细胞和自然杀伤（NK）细胞。

3.  白细胞的成熟

-   淋巴细胞：
    -   B细胞：在骨髓中成熟，并在接触抗原后在淋巴结和脾脏中进一步发展。
    -   T细胞：在骨髓中发育成幼稚T细胞，然后迁移到胸腺中成熟。
    -   NK细胞：在骨髓中发育成熟。
-   髓系细胞：
    -   中性粒细胞、嗜酸性粒细胞和嗜碱性粒细胞：在骨髓中发育成熟，然后释放到血液循环中。
    -   单核细胞：在骨髓中发育成熟，进入血液循环后迁移到组织中，成为巨噬细胞或树突状细胞。

## Acute Myeloid Leukemia

急性髓系白血病（Acute Myeloid Leukemia, AML）主要涉及骨髓中的**髓系白细胞**(Myeloid White Blood Cells)。在AML中，骨髓生成的是异常的髓系前体细胞，这些细胞通常会发展成成熟的白细胞，但在AML中，它们变得异常并不能正常成熟。

### AML中受影响的细胞

髓母细胞 (Myeloblasts)：在AML中，骨髓中的这些幼稚细胞迅速增殖并积聚，阻碍了正常血细胞的生成。这些异常的髓母细胞可能包括非特化的髓系细胞，它们原本应该成熟为多种类型的血细胞，包括某些类型的白细胞、红细胞和血小板。

> 髓母细胞（Myeloblasts）是一种幼稚的骨髓细胞，它们是白细胞发展过程中的早期形态。在正常的血液造血过程中，髓母细胞最终会发育成成熟的白细胞，特别是髓系白细胞，如中性粒细胞、嗜酸性粒细胞和嗜碱性粒细胞。

然而，髓母细胞本身并不是功能成熟的白细胞。它们属于前体细胞，意味着它们是在成熟白细胞形成过程中的一个阶段。在健康的骨髓中，髓母细胞会经历一个有序的成熟过程，最终成为能够正常执行免疫功能的成熟白细胞。

### AML的影响

由于这些异常髓母细胞在骨髓中的积聚，正常的血细胞生成受到抑制，导致贫血、易感染和出血倾向等症状。这些未成熟的细胞也可能进入血液循环和其他身体部位，影响其他器官的功能。

### R/R AML 和 ND AML

R/R AML（复发/难治性急性髓性白血病）和ND AML（新诊断的急性髓性白血病）代表了急性髓性白血病在不同阶段或情况下的两种状态：

1.  **R/R AML（复发/难治性急性髓性白血病）**：

    -   **复发性AML** 指的是在治疗后白血病细胞在血液和骨髓中再次出现的情况，即病情在一段时间的缓解后又回归。这表明白血病最初对治疗有反应，但最终又复发。

    -   **难治性AML** 描述了白血病对治疗没有反应或在最初成功后停止响应的情况。基本上，白血病细胞对正在使用的治疗方法产生了抵抗。

2.  **ND AML（新诊断的急性髓性白血病）**：

    -   这个术语用于那些最近被诊断出患有AML且尚未接受过白血病治疗的患者。

    -   针对ND AML的治疗方法通常与R/R AML的治疗方法不同，因为它们是针对那些尚未接触或可能对某些治疗方法产生抵抗的患者设计的。

理解这两种分类之间的区别对于制定治疗策略至关重要。由于药物抵抗性的存在或病情的复发，R/R AML通常需要比ND AML更激进或不同的治疗方法。

## Chronic Lymphocytic Leukemia

### 特点：

-   CLL主要影响B细胞，这是一种淋巴细胞，负责产生抗体。
-   病变细胞通常在骨髓中缓慢增长并逐渐积累。
-   CLL多见于中老年人，是最常见的成人白血病类型之一。

### 危害：

-   免疫功能受损，导致感染风险增加。
-   可能导致贫血和血小板减少。
-   CLL进展缓慢，但在一些情况下可能转化为更为侵袭性的白血病或淋巴瘤。
-   长期积累的异常淋巴细胞可能导致脾脏和淋巴结肿大。

### CLL与AML的区别

-   细胞类型：CLL影响淋巴细胞（主要是B细胞），而AML影响髓系细胞。
-   进展速度：CLL通常进展缓慢，而AML进展迅速。
-   临床表现：CLL的症状可能在早期不明显，而AML的症状通常迅速出现并加剧。
-   治疗方法：CLL和AML的治疗方法不同，反映了它们的生物学差异。
