---
title: "Lymphoma"
---

淋巴瘤（Lymphoma）是一种发生在淋巴系统的恶性肿瘤，主要影响淋巴细胞。淋巴细胞是免疫系统的重要组成部分，负责抵御感染和维持免疫平衡。淋巴瘤的发展可能导致免疫系统功能受损，影响身体对感染和疾病的抵抗力。

## 淋巴瘤的主要类型

淋巴瘤主要分为两大类：霍奇金淋巴瘤（Hodgkin's Lymphoma, HL）和非霍奇金淋巴瘤（Non-Hodgkin's Lymphoma, NHL）。

+ 霍奇金淋巴瘤 (HL)：其特征性标志是里德-斯登伯格细胞（Reed-Sternberg cells）的存在。HL通常从一个淋巴结开始，并可能蔓延到相邻的淋巴结。它的发病机制比较典型，治疗反应良好。
+ 非霍奇金淋巴瘤 (NHL)：是一组更为多样化的淋巴瘤，包括多种不同类型，如滤泡淋巴瘤、弥漫大B细胞淋巴瘤等。NHL可能发展迅速（高度恶性）或缓慢（低度恶性）。


## 症状
淋巴瘤的常见症状可能包括：

+ 淋巴结无痛性肿大。
+ 持续性发热。
+ 体重无缘无故下降。
+ 夜间盗汗。
+ 疲劳或乏力。
+ 咳嗽或呼吸困难（如果胸部淋巴结受累）。

## 治疗
淋巴瘤的治疗选择取决于多种因素，如淋巴瘤的类型、疾病阶段、患者的年龄和整体健康状况。治疗方法可能包括：

+ 化疗：是淋巴瘤治疗的主要方式。
+ 放疗：特别是对于霍奇金淋巴瘤。
+ 生物疗法/靶向治疗：利用药物针对癌细胞的特定特征。
+ 干细胞移植：在某些高风险或复发性病例中。

## 主要的非霍奇金淋巴瘤亚型

+ 弥漫大B细胞淋巴瘤（Diffuse Large B-Cell Lymphoma, DLBCL）：这是最常见的NHL类型，其特征是快速增长的大B细胞。
+ 滤泡性淋巴瘤（Follicular Lymphoma）：相对较常见的一种NHL，通常生长较慢，涉及小淋巴细胞。
+ 套细胞淋巴瘤（Mantle Cell Lymphoma）：一种相对少见的NHL，以套细胞（位于淋巴滤泡边缘区的B细胞）的异常增生为特征。
+ 小淋巴细胞性淋巴瘤（Small Lymphocytic Lymphoma, SLL）：与慢性淋巴细胞性白血病（CLL）密切相关，通常表现为慢性病程。
+ Burkitt淋巴瘤：一种高度恶性的NHL，特别是在儿童中。
+ 骨髓外边缘区B细胞淋巴瘤（Extranodal Marginal Zone B-Cell Lymphoma）：通常发生在淋巴结外的组织，如胃、肠道。
+ 皮肤T细胞淋巴瘤（Cutaneous T-Cell Lymphomas）：一组以皮肤为主要受累器官的淋巴瘤。

## Diffuse Large B-Cell Lymphoma

弥漫大B细胞淋巴瘤（Diffuse Large B-Cell Lymphoma, DLBCL）是最常见的非霍奇金淋巴瘤（NHL）类型之一，占所有NHL的约30-40%。DLBCL起源于B淋巴细胞，这种类型的淋巴瘤特点是淋巴结内或淋巴组织外的快速增长。

### 特点

+ 细胞特性：DLBCL由体积较大的B细胞组成，这些细胞的大小通常是正常淋巴细胞的两倍或更大。
+ 增长速度：DLBCL是一种快速增长的淋巴瘤，可以在短时间内引起显著症状。
+ 发病部位：虽然通常首先影响淋巴结，但也可以涉及其他器官，如胃肠道、骨髓、脾脏或中枢神经系统。

### 症状
DLBCL的症状可能包括：

+ 无痛性淋巴结肿大。
+ 发热、夜间盗汗和体重减轻（所谓的“B症状”）。
+ 疲劳和乏力。
+ 在受累器官（如胃肠道、骨髓）的情况下可能有特定症状。

## Mantle Cell Lymphoma

套细胞淋巴瘤（Mantle Cell Lymphoma, MCL）是一种非霍奇金淋巴瘤（NHL）的类型，相对罕见。它起源于B淋巴细胞，特别是那些位于淋巴结的套区（Mantle Zone）的B细胞。MCL的一些关键特点和治疗方法如下：

### 特点

+ 细胞来源：MCL源自B淋巴细胞，特别是淋巴滤泡的套区细胞。
+ 基因变异：MCL通常与某些特定的基因变异相关，尤其是t(11;14)(q13;q32)易位，导致+ 环状蛋白激酶-1（Cyclin D1）的过度表达。
+ 临床表现：MCL的临床表现可能包括淋巴结肿大、脾脏肿大，以及其他与免疫系统相关的症状。有时，肠道也可能受到影响。

### 危害

+ 侵袭性：MCL是一种侵袭性癌症，可能迅速进展。
+ 免疫系统受损：MCL影响免疫系统，增加感染的风险。
+ 晚期发现：MCL在诊断时常处于晚期。

### 治疗

+ 化疗：是MCL治疗的主要方法，通常使用多药联合化疗方案。
+ 靶向治疗：如BTK（布鲁顿酪氨酸激酶）抑制剂，用于治疗特定患者群体。
+ 生物疗法：包括利用抗体药物，如利妥昔单抗。
+ 干细胞移植：在部分患者中，尤其是较年轻或身体状况较好的患者，可以考虑干细胞移植。

## Small Lymphocytic Lymphoma
淋巴细胞性淋巴瘤（Small Lymphocytic Lymphoma, SLL）是一种非霍奇金淋巴瘤（NHL）的亚型，主要影响淋巴系统中的小淋巴细胞。SLL与慢性淋巴细胞性白血病（CLL）密切相关，两者在生物学上几乎是相同的疾病，区别主要在于癌细胞在身体中的分布。

### 特点

+ 细胞类型：SLL影响成熟的B细胞，这些细胞在体内免疫反应中扮演重要角色。
+ 病变位置：SLL主要表现为淋巴结和脾脏的肿大，而不是血液中白细胞数量的显著增加（这是CLL的特点）。
+ 发展速度：SLL通常是一种低度恶性疾病，发展缓慢。

### 症状
SLL的典型症状包括：

+ 无痛性淋巴结肿大。
+ 脾脏肿大。
+ 由于免疫系统受损，可能导致易感染。
