---
title: "Myelodysplastic Syndromes (MDS)"
---

骨髓增生异常综合征（Myelodysplastic Syndromes, MDS）是一组多发性的骨髓障碍，这些障碍由于骨髓中造血细胞的异常而导致血细胞的不正常发育。MDS可影响体内所有类型的血细胞，包括红细胞、白细胞和血小板。

## 成因

MDS的确切成因不完全清楚，但已知以下因素可能与其发展有关：

-   遗传因素：某些遗传改变被认为与MDS的发展有关。
-   化学物质暴露：长期暴露于化学物质，如苯和某些农药。
-   放射线暴露：如接受过放疗。
-   以前的化疗：某些类型的化疗药物。

## 症状

MDS的症状通常与低血细胞计数有关，包括：

-   贫血：由于红细胞减少，导致乏力和呼吸困难。
-   易感染：由于白细胞减少。
-   出血倾向：由于血小板减少，导致容易出现瘀伤和出血。

## 分类

MDS可以根据骨髓和外周血液中的异常细胞类型以及这些细胞的比例来分类。有多种不同的MDS亚型，它们的预后和治疗方式可能不同。

1.  难治性贫血（Refractory Anemia, RA）：这种亚型主要影响红细胞，导致贫血。
2.  难治性贫血伴有环状铁粒幼细胞（Refractory Anemia with Ring Sideroblasts, RARS）：除了贫血外，骨髓中还出现环状铁粒幼细胞（铁粒在红细胞前体细胞中异常积聚）。
3.  难治性贫血伴血小板增多（Refractory Anemia with Thrombocytosis, RART）：这种亚型涉及贫血和血小板数量异常增多。
4.  难治性细胞性血液病（Refractory Cytopenia with Multilineage Dysplasia, RCMD）：影响多个血细胞系列（红细胞、白细胞和血小板），并伴有细胞形态学上的异常。
5.  难治性细胞性血液病伴有异形细胞（Refractory Cytopenia with Multilineage Dysplasia and Ring Sideroblasts, RCMD-RS）：类似于RCMD，但同时在骨髓中存在环状铁粒幼细胞。
6.  难治性血细胞减少症（Refractory Cytopenia with Unilineage Dysplasia, RCUD）：只影响一种血细胞系列（红细胞、白细胞或血小板）。
7.  骨髓增生异常综合征，未分类（Myelodysplastic Syndrome, Unclassifiable, MDS-U）：不能归入其他任何子类型的MDS。
8.  骨髓增生异常综合征伴有隔离性染色体异常，仅限于5q-（Myelodysplastic Syndrome with Isolated del(5q)）：这种亚型有特定的染色体5q缺失，通常有较好的预后。

## 治疗

MDS的治疗取决于多种因素，包括疾病的具体类型、患者的年龄和总体健康状况。治疗方法可能包括：

-   支持性治疗：如输血和使用生长因子。
-   药物治疗：包括免疫抑制剂和化疗药物。
-   干细胞移植：对于某些适合的患者来说，干细胞移植可能提供治愈的可能。

MDS是一个复杂的疾病群，需要专业医生的评估和治疗。由于MDS有可能发展成急性髓系白血病（[AML](Leukemia.qmd#acute-myeloid-leukemia)），因此密切监测和适时治疗十分重要。

## 与AML的区别

骨髓增生异常综合征（Myelodysplastic Syndromes, MDS）和急性髓系白血病（[Acute Myeloid Leukemia, AML](Leukemia.qmd#acute-myeloid-leukemia)）是两种不同的血液疾病，它们在发病机制、临床表现和治疗策略上有明显的区别。

-   MDS:
    -   特点：MDS是一组骨髓功能障碍的疾病，主要特征是骨髓中血细胞（红细胞、白细胞和血小板）的不成熟和功能异常。
    -   发病机制：MDS的造血细胞具有异常的增生和成熟过程，这通常导致低血细胞计数。
    -   症状：症状可能包括贫血、易感染和出血倾向。
    -   治疗：治疗可能包括支持性治疗（如输血和使用生长因子）、药物治疗和干细胞移植。
    -   转化风险：MDS可能会发展成AML，但不是所有MDS患者都会发展成AML。
-   AML
    -   特点：AML是一种急性血液癌症，主要特征是骨髓中未成熟白血细胞（髓母细胞）的快速增生。
    -   发病机制：AML中的髓母细胞迅速增加，抑制了正常血细胞的产生。
    -   症状：症状包括严重的贫血、感染风险增加和出血问题。
    -   治疗：治疗通常包括强化的化疗和可能的干细胞移植。
    -   急性发展：AML通常需要紧急治疗，因为病情可能迅速恶化。

主要区别

-   疾病进展：MDS通常是慢性的，可能会逐渐恶化；而AML是急性发展，通常需要立即治疗。
-   血液细胞的影响：MDS主要影响血细胞的成熟和功能；而AML主要是未成熟白血细胞的无控制增生。
-   治疗和预后：两者的治疗方法和预后差异较大。
