---
title: "Melanoma"
---

黑色素瘤（Melanoma）是一种发生在皮肤上的恶性肿瘤，起源于产生皮肤颜色的黑色素细胞。相比于其他类型的皮肤癌，如基底细胞癌或鳞状细胞癌，黑色素瘤具有更高的侵袭性和更大的转移潜力。由于其快速增长和高度恶性，黑色素瘤被视为最严重的皮肤癌形式之一。了解黑色素瘤的关键特点和治疗方法对于及早诊断和有效治疗至关重要。

## 关键特点

-   起源：黑色素瘤起源于黑色素细胞，这些细胞负责给皮肤、毛发和眼睛提供颜色。
-   外观：黑色素瘤通常表现为新出现或已有痣的变化，包括大小、形状、颜色的改变，或不规则边缘。
-   ABCDE规则：用于评估痣是否为黑色素瘤的迹象：
    -   A（不对称性 Asymmetry）
    -   B（边界不规则 Border irregularity）
    -   C（颜色不均 Color variation）
    -   D（直径 Diameter，通常大于6毫米）
    -   E（演变 Evolving，任何变化）

## 主要类型

黑色素瘤（Melanoma）根据其生长模式和位置，可以分为几种不同的类型。每种类型的黑色素瘤都有其独特的特征和临床表现。主要类型包括：

-   浅表扩散性黑素瘤（Superficial Spreading Melanoma, SSM）：浅表扩散性黑色素瘤是最常见的黑色素瘤类型。这种黑色素瘤通常表现为平坦或几乎没有凸起的病变，通常有不规则的边界和颜色变化，并且一开始会沿着皮肤的最上层，即表皮扩散几个月到几年，然后才浸入皮肤。根据美国国家癌症研究所(NCI)的数据，70%的确诊病例为浅表扩散型黑素瘤。
-   结节性黑色素瘤（Nodular Melanoma, NM）：结节性黑素瘤是一种最常见于躯干、头部或颈部的黑色素瘤，占所有黑色素瘤的10% - 15%。这种黑色素瘤通常表现为蓝黑色的圆形结节，5%的情况下病变呈粉红色或红色。在首次出现在皮肤表面后，结节性黑色素瘤可能会迅速生长到更深的皮肤层，表现为肿块。结节性黑色素瘤侵袭得更早，也比其他黑色素瘤往往预后更差。
-   恶性雀斑样痣黑素瘤（Lentigo Maligna Melanoma, LMM）：恶性雀斑样痣黑素瘤通常需要很多年才能形成，最常见于人的胳膊、腿、脸、脖子和其他暴露在阳光下的部位，占所有黑色素瘤的5%。由于长期暴露在阳光下，这种类型黑色素瘤的风险会随着年龄的增长而增加，老年人发病最多。
-   肢端型黑色素瘤（Acral Lentiginous Melanoma, ALM）：肢端型黑色素瘤在深色肤色人群和亚洲人中最常见，根据NCI的数据，这种类型的黑色素瘤在非裔美国人所有病例中占70%，在亚洲所有病例中占46%，在白种人所有病例中只占的1%。在所有黑素瘤中，肢端型黑素瘤只占不到5%。手掌、脚底和指甲下可发现横向小扁豆性黑色素瘤。
-   黏膜黑色素瘤（Mucosal Melanoma）：与皮肤中的黑色素细胞一样，粘膜中的黑色素细胞也可能癌变，也就是黏膜型黑色素瘤。黏膜黑色素瘤是一种罕见的黑色素瘤，发生在身体的粘膜表面，常见于鼻窦、鼻腔、口腔、阴道、肛门和其他区域。
-   眼部黑色素瘤（Ocular Melanoma）：眼部黑色素瘤是在原发在眼部的黑色素瘤，相对少见，仅占所有黑色素瘤病例的3%。在美国，每年约有2000例眼部黑色素瘤被诊断出来。然而，眼黑色素瘤是成人最常见的原发性眼内癌(肿瘤开始于眼睛)。眼黑色素瘤又称葡萄膜黑色素瘤，因为它发生在眼睛的葡萄膜部位。

## 危害

-   高度侵袭性：黑色素瘤能快速生长并侵入周围组织。
-   转移潜力：黑色素瘤可以通过淋巴系统或血液转移到身体其他部位，包括肺、肝、脑和骨骼。

## 治疗

-   外科手术：早期黑色素瘤通常通过外科手术切除。
-   放疗：用于控制局部或转移性黑色素瘤。
-   化疗和辅助治疗：
    -   辅助性干扰素（Interferon alfa-2b）治疗。
    -   辅助性化疗药物，如达卡巴嗪（Dacarbazine）。
-   靶向治疗：
    -   BRAF抑制剂：如维莫非尼（[Zelboraf](../compound/Zelboraf.qmd) (Vemurafenib)）、达巴非尼（[Tafinlar](../compound/Tafinlar.qmd) (Dabrafenib)）。
    -   MEK抑制剂：如曲美替尼（[Mekinist](../compound/Mekinist.qmd) (Trametinib)）、考比替尼（[Cotellic](../compound/Cotellic.qmd) (Cobimetinib)）。
-   免疫治疗：
    -   PD-1抑制剂：如纳武利尤单抗（[Opdivo](../compound/Opdivo.qmd) (Nivolumab)）、帕波利珠单抗（[Keytruda](../compound/Keytruda.qmd) (Pembrolizumab)）。
    -   CTLA-4抑制剂：如伊匹单抗（[Yervoy](../compound/Yervoy.qmd) (Ipilimumab)）。

## 预防和筛查

-   日常自我检查：定期检查皮肤上的痣和斑点，留意任何变化。
-   专业皮肤检查：定期由皮肤科医生进行全面的皮肤检查。
-   防晒和皮肤保护：避免过度曝晒阳光和使用防晒霜，特别是在紫外线较强的时段。
