---
title: "Thrombosis"
---

## 关键特点

-   发生部位：血栓可以在身体的任何血管中形成，最常见于腿部的深静脉（深静脉血栓形成，DVT）和心脏的冠状动脉。
-   触发因素：血流缓慢、血管损伤或血液凝固性增加等因素都可以促使血栓形成。

## 主要类型

-   静脉血栓形成（Venous Thrombosis）：
    -   深静脉血栓形成（Deep Vein Thrombosis, DVT）：指发生在体内深静脉的血栓，尤其是腿部或骨盆区域的静脉。
    -   肺栓塞（Pulmonary Embolism, PE）：是由脱落的血栓（通常来源于腿部或其他深静脉的DVT）引起的，这些血栓随血液流动到肺部并阻塞肺动脉。
-   动脉血栓形成（Arterial Thrombosis）：
    -   冠状动脉血栓形成（Coronary Artery Thrombosis）：指发生在供血心脏的冠状动脉中的血栓，可能导致心脏病发作。
    -   脑动脉血栓形成（Cerebral Arterial Thrombosis）：指发生在供血大脑的动脉中的血栓，可能导致中风。

## 危害

-   组织缺血：血栓阻塞血管，导致组织缺血和损伤。
-   器官功能受损：如果血栓影响重要器官（如心脏、大脑、肺），可能导致严重的健康问题，甚至死亡。
-   肺栓塞：如果腿部的血栓脱落并随血液流动到肺部，可能引起肺栓塞，这是一种紧急情况。

## 治疗

-   抗凝治疗：使用抗凝血药物（如华法林、肝素）来防止新血栓的形成或现有血栓的增大。
-   溶栓治疗：在某些情况下，使用溶栓剂来溶解血栓。
-   手术治疗：在严重或复杂的情况下，可能需要手术移除血栓或置入血管支架。

## 药物

-   华法林（Warfarin）
-   肝素（Heparin）和低分子肝素（如依诺肝素）
-   新型口服抗凝剂（如达比加群(Dabigatran Etexilate)、利伐沙班([Rivaroxaban/Xarelto](../compound/Xarelto.qmd)), 阿哌沙班([Apixaban/Eliquis](../compound/Eliquis.qmd))）

## 预防

-   积极生活方式：保持活跃，避免长时间久坐。
-   健康饮食：均衡饮食，维持健康体重。
-   定期检查：对于有血栓风险的个体，定期进行医学检查和评估。
-   停止吸烟：吸烟是血栓形成的重要风险因素。
