---
title: "Pharma Note"
---

## Guidance

[FDA Guidance website](https://www.fda.gov/regulatory-information/search-fda-guidance-documents)

### **Oncologic Drugs Advisory Committee (ODEC)**

2024 Meeting Materials

-   [September 26, 2024: Meeting of the Oncologic Drugs Advisory Committee Meeting Announcement](https://www.fda.gov/advisory-committees/advisory-committee-calendar/september-26-2024-meeting-oncologic-drugs-advisory-committee-meeting-announcement-09262024 "September 26, 2024: Meeting of the Oncologic Drugs Advisory Committee Meeting Announcement - 09/26/2024")

    ::: {.callout-note collapse="true" title="Materials"}
    -   Morning:
        -   BeiGene: [Sponsor Briefing Document](https://drive.google.com/file/d/11z1VIWMlud_NNw03lr-22_qr8VW39NnY/view?usp=drive_link), [Presentation](https://drive.google.com/file/d/11m5bkYoKGVYrbbpgtspbMOBvUeYzXHdm/view?usp=drive_link)
        -   [BMS](../company/BMS.qmd): [Sponsor Briefing Document](https://drive.google.com/file/d/11nxygmKCl0YErSe35A5LUB1Y9u11WJAW/view?usp=drive_link), [Presentation](https://drive.google.com/file/d/12Nhm1Lij09t3kbGdfLQzHR6xWsOqXWdn/view?usp=drive_link)
        -   [Merck](../company/Merck.qmd): [Sponsor Briefing Document](https://drive.google.com/file/d/12VNIw75EoMKZmDxyKNU0GCeHXePyeFf9/view?usp=drive_link), [Presentation](https://drive.google.com/file/d/126xWKNxsvuESx3t8dnMrENyeKZ31qkOF/view?usp=drive_link)
        -   FDA: [Briefing Document](https://drive.google.com/file/d/12_Oe8YOMX0RkDQIoOb-r3dM6lIJ793FF/view?usp=drive_link), [Presentation](https://drive.google.com/file/d/11r7By64gxcpy8cLTBuMwJo58YzFprj18/view?usp=drive_link)
    -   Afternoon:
        -   BeiGene: [Sponsor Briefing Document](https://drive.google.com/file/d/12PjByaF1pDgSoTE2FXbHNf-4rF6EjyaJ/view?usp=drive_link), [Presentation](https://drive.google.com/file/d/11kEKjzdLnNxtyFjDjwcP5iAw8-9B7rT7/view?usp=drive_link)
        -   BMS: [Sponsor Briefing Document](https://drive.google.com/file/d/12K5pz6HkqG_yGYxzWUVXS-Y7AMpPhcC7/view?usp=drive_link), [Presentation](https://drive.google.com/file/d/11jUFK5hWg20-YQrmT_6bSar6Avw792q-/view?usp=drive_link)
        -   Merck: [Sponsor Briefing Document](https://drive.google.com/file/d/123rY-QXNsknyDW0RGY6ligP8eA4TWh9t/view?usp=drive_link), [Presentation](https://drive.google.com/file/d/11iabS6S6dIkMDOQnDNSUR3MhwOQusjsn/view?usp=drive_link)
        -   FDA: [Briefing Document](https://drive.google.com/file/d/12H0AQrgL3WS_5qRikSAojOJ8g-Vak7l2/view?usp=drive_link), [Presentation](https://drive.google.com/file/d/12LYrnYiDjyv5I0_JA2M-bXQNTtF9mbAm/view?usp=drive_link)
    :::

    ::: {.callout-warning collapse="true" title="Agenda"}
    During the morning session, the Committee will discuss the use of immune checkpoint inhibitors in patients with unresectable or metastatic gastric and gastroesophageal junction adenocarcinoma. The current labeling for approved checkpoint inhibitors in this indication reflect broad approvals in the intent to treat patient populations agnostic of programmed death cell ligand-1 (PD-L1) expression. Cumulative data has shown that PD-L1 expression appears to be a predictive biomarker of treatment efficacy in this patient population; however, clinical trials have used different approaches to assess PD-L1 expression and different thresholds to define PD-L1 positivity. FDA would like the Committee’s opinion on the:

    -   adequacy of PD-L1 expression as a predictive biomarker for patient selection in this patient population,
    -   differing risk-benefit assessments in different subpopulations defined by PD-L1 expression, and
    -   adequacy of the cumulative data to restrict the approvals of immune checkpoint inhibitors based on PD-L1 expression.

    The Committee will discuss the existing supplemental biologics license applications (sBLA) which were approved for patients with previously untreated HER2-negative unresectable or metastatic gastric or gastroesophageal adenocarcinoma:

    -   sBLA 125554/S-091 for OPDIVO (nivolumab) injection, submitted by Bristol Myers-Squibb Co. and
    -   sBLA 125514/S-143 for KEYTRUDA (pembrolizumab) injection, submitted by Merck Sharp & Dohme LLC, a subsidiary of Merck & Co., Inc.

    The Committee will also discuss BLA 761417 for tislelizumab injection, submitted by BeiGene USA, Inc., for the same proposed indication.

    During the afternoon session, the Committee will discuss the use of immune checkpoint inhibitors in patients with metastatic or unresectable esophageal squamous cell carcinoma. The current labeling for approved checkpoint inhibitors in this indication reflect broad approvals in the intent to treat patient populations agnostic of programmed death cell ligand-1 (PD-L1) expression. Cumulative data has shown that PD-L1 expression appears to be a predictive biomarker of treatment efficacy in this patient population; however, clinical trials have used different approaches to assess PD-L1 expression and different thresholds to define PD-L1 positivity. FDA would like the Committee’s opinion on the:

    -   adequacy of PD-L1 expression as a predictive biomarker for patient selection in this patient population,
    -   differing risk-benefit assessments in different subpopulations defined by PD-L1 expression, and
    -   adequacy of the cumulative data to restrict the approvals of immune checkpoint inhibitors based on PD-L1 expression.

    The Committee will discuss the existing sBLAs which were approved for patients with previously untreated unresectable or metastatic esophageal squamous cell carcinoma:

    -   sBLA 125514/S-096 for KEYTRUDA (pembrolizumab) injection, submitted by Merck Sharp & Dohme LLC, a subsidiary of Merck & Co., Inc.;
    -   sBLAs 125554/S-105 and S-106 for OPDIVO (nivolumab) injection, submitted by Bristol Myers-Squibb Co.; and
    -   sBLA 125377/S-122 for YERVOY (ipilimumab) injection, submitted by Bristol Myers-Squibb Co.

    The Committee will also discuss the new BLA 761380 for tislelizumab, submitted by BeiGene USA, Inc., for the same proposed indication.
    :::

-   [July 25, 2024 Meeting of the Oncologic Drugs Advisory Committee Meeting Announcement](https://www.fda.gov/advisory-committees/updated-agenda-information-july-25-2024-meeting-oncologic-drugs-advisory-committee-meeting "UPDATED AGENDA INFORMATION : July 25, 2024 Meeting of the Oncologic Drugs Advisory Committee Meeting Announcement - 07/25/2024")

-   [May 22, 2024: Meeting of the Pediatric Oncology Subcommittee of the Oncologic Drugs Advisory Committee Meeting Announcement](https://www.fda.gov/advisory-committees/advisory-committee-calendar/may-22-2024-meeting-pediatric-oncology-subcommittee-oncologic-drugs-advisory-committee-meeting "May 22, 2024: Meeting of the Pediatric Oncology Subcommittee of the Oncologic Drugs Advisory Committee Meeting Announcement - 05/22/2024")

-   [April 12, 2024 Meeting of the Oncologic Drugs Advisory Committee Meeting Announcement](https://www.fda.gov/advisory-committees/advisory-committee-calendar/april-12-2024-meeting-oncologic-drugs-advisory-committee-meeting-announcement-04122024 "April 12, 2024 Meeting of the Oncologic Drugs Advisory Committee Meeting Announcement - 04/12/2024")

    ::: {.callout-note collapse="true" title="Materials"}
    -   [Drug Topic: Use of Minimal Residual Disease (MRD) as an Endpoint in Multiple Myeloma Clinical Trials](https://drive.google.com/file/d/11Cnvz6aOgCJnmc_jcg40GbF9g5ab0ITH/view?usp=sharing)

    -   [FDA Slides](https://drive.google.com/file/d/11Rtm_TW7A0sxZiGKKRpy7tu3yTM4AJzA/view?usp=sharing)

    -   [Presentation: i2TEAMM Presentation to Support MRD as Accelerated Approval Endpoint](https://drive.google.com/file/d/11JYWuau38SKWoP6Prl2hE2-i2T_FO2DD/view?usp=sharing)

    -   [Evaluating Minimal Residual Disease as an Intermediate Clinical Endpoint for Multiple Myeloma: The EVIDENCE Meta-Analysis](https://drive.google.com/file/d/11ajUHGAD2e2PPbJHz24MjIwKtmiSatcI/view?usp=sharing)
    :::

    ::: {.callout-warning collapse="true" title="Agenda"}
    The meeting presentations will be heard, viewed, captioned, and recorded through an online teleconferencing and/or video conferencing platform. The Committee will discuss the use of **minimal residual disease (MRD)** as an endpoint in [multiple myeloma](../disease/multiple_myeloma.qmd) clinical trials, including considerations regarding timing of assessment, patient populations, and trial design for future studies that intend to use MRD to support accelerated approval of a new product or a new indication.
    :::

-   [March 15, 2024: Meeting of the Oncologic Drugs Advisory Committee Meeting Announcement](https://www.fda.gov/advisory-committees/advisory-committee-calendar/march-15-2024-meeting-oncologic-drugs-advisory-committee-meeting-announcement-03152024 "March 15, 2024: Meeting of the Oncologic Drugs Advisory Committee Meeting Announcement - 03/15/2024")

    ::: {.callout-note collapse="true" title="Material"}
    -   [Sponsor Briefing Document for ABECMA](https://drive.google.com/file/d/11DYeI5K_DolXtcjfQzHwtRaXBfHPCVGz/view?usp=sharing)

    -   [FDA Presentation for Carvykti](https://drive.google.com/file/d/12f5wMJAdD-87MIAQ6xMz0AxSobPZqY-1/view?usp=sharing)

    -   [FDA Presentation for Abecma](https://drive.google.com/file/d/12g0QsUiYa3wPFJLhEnGOCarEggE_SuQs/view?usp=sharing)
    :::

    ::: {.callout-warning collapse="true" title="Agenda"}
    The meeting presentations will be heard, viewed, captioned, and recorded through an online teleconferencing platform. During the morning session, the Committee will discuss supplemental biologics license application (sBLA) 125746.74 for CARVYKTI (ciltacabtagene autoleucel), suspension for intravenous infusion, submitted by Janssen Biotech, Inc. The proposed indication for this product is for the treatment of adult patients with relapsed or refractory multiple myeloma, who have received at least one prior line of therapy, including a proteasome inhibitor, and an immunomodulatory agent, and are refractory to lenalidomide. The Committee will have a general discussion focused on the overall survival data in the Study MMY3002 (CARTITUDE-4) and the risk and benefit of ciltacabtagene autoleucel in the intended population. During the afternoon session, the Committee will discuss sBLA 125736.218 for **ABECMA** (idecabtagene vicleucel), suspension for intravenous infusion, submitted by Celgene Corp., a Bristol-Myers Squibb Co. The proposed indication is for the treatment of adult patients with relapsed or refractory multiple myeloma who have received an immunomodulatory agent, a proteasome inhibitor, and an anti-CD38 monoclonal antibody. The Committee will have a general discussion focused on the overall survival data in the Study MM-003 (KarMMa-3) and the risk and benefit of idecabtagene vicleucel in the intended population.
    :::

-   [March 14, 2024: Meeting of the Oncologic Drugs Advisory Committee Meeting Announcement](https://www.fda.gov/advisory-committees/advisory-committee-calendar/march-14-2024-meeting-oncologic-drugs-advisory-committee-meeting-announcement-03142024 "March 14, 2024: Meeting of the Oncologic Drugs Advisory Committee Meeting Announcement - 03/14/2024")

## Reference

[Notion Pharam Notes](https://www.notion.so/d5e722fd18e1441191c7aa019dcfde48?v=d7caa4be5e534e51a342e24b8549696e&pvs=4)
